//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.POSBLUE.Data.DataBaseContext.PLG
{
    using System;
    using System.Collections.Generic;
    
    public partial class PL_VoucherCardTrans
    {
        public long ID { get; set; }
        public string Partner { get; set; }
        public string SeriNo { get; set; }
        public string StoreNo { get; set; }
        public string PosID { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<bool> Status { get; set; }
        public string FunctionName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UserName { get; set; }
    }
}
