//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.EInvoices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public int ID { get; set; }
        public string BranchNo { get; set; }
        public string BranchName { get; set; }
        public string Address { get; set; }
        public string CompTaxCode { get; set; }
        public string ETaxAccName { get; set; }
        public string ETaxAccPass { get; set; }
        public string ETaxWSName { get; set; }
        public string ETaxWSPass { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string BranchNoWCM { get; set; }
    }
}
