//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.EInvoices
{
    using System;
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EInvoiceContainer : DbContext
    {
        public static string setDB1 = @"" + ConfigurationManager.AppSettings["setDB1"];
        public static string setDB2 = @"" + ConfigurationManager.AppSettings["setDB2"];
        public EInvoiceContainer()
            : base("name=EInvoiceContainer")
        {
        }
        public EInvoiceContainer(string IPServer)
                : base("name=" + (IPServer == setDB1 ? "SetDB1_EInvoice"
                               : (IPServer == setDB2 ? "SetDB2_EInvoice"
                               : "SetDB1_EInvoice"))
                      )
        {
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InvoiceCreated> InvoiceCreateds { get; set; }
        public virtual DbSet<InvoiceHeaderEOD> InvoiceHeaderEODs { get; set; }
        public virtual DbSet<InvoiceHeaderNormal> InvoiceHeaderNormals { get; set; }
        public virtual DbSet<InvoiceLineEOD> InvoiceLineEODs { get; set; }
        public virtual DbSet<InvoiceLineNormal> InvoiceLineNormals { get; set; }
        public virtual DbSet<InvoiceNormalOrderProcess> InvoiceNormalOrderProcesses { get; set; }
        public virtual DbSet<OrderNoCreatedInvoice> OrderNoCreatedInvoices { get; set; }
        public virtual DbSet<OrderNoCreatedInvoiceOther> OrderNoCreatedInvoiceOthers { get; set; }
    }
}
