//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.EInvoices
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceLineNormal
    {
        public int ID { get; set; }
        public string DocumentNo { get; set; }
        public string Key { get; set; }
        public string Code { get; set; }
        public string ProdName { get; set; }
        public string ProdUnit { get; set; }
        public double ProdQuantity { get; set; }
        public double ProdPrice { get; set; }
        public double Total { get; set; }
        public double VATRate { get; set; }
        public double VATAmount { get; set; }
        public double Amount { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<double> VatVinIDAmount { get; set; }
        public Nullable<double> NetVinIDAmount { get; set; }
        public Nullable<double> TotalVinIDAmount { get; set; }
        public Nullable<int> VatCode { get; set; }
        public string AppCode { get; set; }
    }
}
