//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.EInvoices
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceHeaderEOD
    {
        public int ID { get; set; }
        public string DocumentNo { get; set; }
        public string Key { get; set; }
        public string Salt { get; set; }
        public string Type { get; set; }
        public string InvoicePattern { get; set; }
        public string SerialNo { get; set; }
        public string InvoiceNo { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string CusCode { get; set; }
        public string CusName { get; set; }
        public string CusCom { get; set; }
        public string CusAddress { get; set; }
        public string CusPhone { get; set; }
        public string CusTaxCode { get; set; }
        public string PaymentMethod { get; set; }
        public double GrossValueNonTax { get; set; }
        public double GrossValue { get; set; }
        public double VatAmount0 { get; set; }
        public double GrossValue0 { get; set; }
        public double VatAmount5 { get; set; }
        public double GrossValue5 { get; set; }
        public double VatAmount10 { get; set; }
        public double GrossValue10 { get; set; }
        public double Total { get; set; }
        public double VATRate { get; set; }
        public double VATAmount { get; set; }
        public double Amount { get; set; }
        public string AmountInWords { get; set; }
        public Nullable<System.DateTime> ArisingDate { get; set; }
        public string EmailDeliver { get; set; }
        public string SMSDeliver { get; set; }
        public int VinTich { get; set; }
        public int VinTieu { get; set; }
        public string VinTraLai { get; set; }
        public string Extra { get; set; }
        public string Extra1 { get; set; }
        public Nullable<System.DateTime> BusinessDate { get; set; }
        public string CusBankNo { get; set; }
        public string CusBankName { get; set; }
        public string Extra2 { get; set; }
        public string Extra3 { get; set; }
        public string Extra4 { get; set; }
        public string Extra5 { get; set; }
        public string Extra6 { get; set; }
        public string Extra7 { get; set; }
        public string Extra8 { get; set; }
        public string Extra9 { get; set; }
        public string Extra10 { get; set; }
        public double TotalAmuontNonVAT { get; set; }
        public double TotalAmuont0 { get; set; }
        public double TotalAmuont5 { get; set; }
        public double TotalAmuont10 { get; set; }
        public string ETaxAccName { get; set; }
        public string ETaxAccPass { get; set; }
        public string ETaxWName { get; set; }
        public string ETaxWSPass { get; set; }
        public string BranchNo { get; set; }
        public string Fkey { get; set; }
        public string FkeyListNext { get; set; }
        public string StoreNo { get; set; }
        public Nullable<bool> IsCancel { get; set; }
        public string InvoiceTypeNext { get; set; }
        public string Remark { get; set; }
        public string InvoiceType { get; set; }
        public string InvoiceTypeName { get; set; }
        public Nullable<bool> IsEOD { get; set; }
        public string SaltEncrypt { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<bool> IsSigned { get; set; }
        public Nullable<bool> IsCreateXMLFile { get; set; }
        public Nullable<bool> IsUpload { get; set; }
        public string Operator { get; set; }
        public Nullable<bool> IsAllow { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string FileName { get; set; }
        public Nullable<int> PublishLogID { get; set; }
        public Nullable<bool> IsConvert { get; set; }
        public Nullable<System.DateTime> ConvertDate { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string NoseriCode { get; set; }
        public Nullable<int> VATNumber { get; set; }
        public Nullable<bool> IsDummy { get; set; }
        public string AppCode { get; set; }
        public string URL { get; set; }
        public string InvToken { get; set; }
        public string RefDocumentNo { get; set; }
        public string Result { get; set; }
        public string ObjectID { get; set; }
        public Nullable<double> VatAmount570 { get; set; }
        public Nullable<double> GrossValue570 { get; set; }
        public Nullable<double> VatAmount1070 { get; set; }
        public Nullable<double> GrossValue1070 { get; set; }
        public Nullable<double> VatAmount8 { get; set; }
        public Nullable<double> GrossValue8 { get; set; }
        public Nullable<double> TotalAmuont8 { get; set; }
        public Nullable<int> status_received { get; set; }
        public string status_desc { get; set; }
    }
}
