//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.EInvoices
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderNoCreatedInvoice
    {
        public int ID { get; set; }
        public string Key { get; set; }
        public string DocumentNo { get; set; }
        public Nullable<int> PublishLogID { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<bool> IsAllow { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<bool> IsReturn { get; set; }
        public string StoreNo { get; set; }
        public Nullable<bool> IsEOD { get; set; }
        public Nullable<bool> IsSigned { get; set; }
    }
}
