//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.POSBLUE.Data.DataBaseContext.SaleStaging
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransBluePointOrig
    {
        public long ID { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public int LineNo { get; set; }
        public string OrderNo { get; set; }
        public Nullable<int> OrderLineNo { get; set; }
        public string ItemNo { get; set; }
        public string Uom { get; set; }
        public string Barcode { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<double> LineAmount { get; set; }
        public Nullable<double> ExtraQuantityEarn { get; set; }
        public Nullable<double> ExtraAmountEarn { get; set; }
        public Nullable<double> ExtraQuantityNotEarn { get; set; }
        public Nullable<double> ExtraQuantityNotEarnReturned { get; set; }
        public string OrigOrderNo { get; set; }
        public Nullable<int> OrigLineNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string DiscountType { get; set; }
        public Nullable<int> RecordNo { get; set; }
        public string OrigReferenceNumber { get; set; }
        public string ReferenceNumber { get; set; }
        public string ReceiptNumber { get; set; }
        public string OrigReceiptNumber { get; set; }
        public string VinidCsn { get; set; }
        public string CompanyCodeEmp { get; set; }
        public string EmployeeCode { get; set; }
    }
}
