//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.POSBLUE.Data.DataBaseContext.SaleStaging
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransHeaderStaging
    {
        public byte[] timestamp { get; set; }
        public string OrderNo { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string CustomerNo { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string PhoneNo { get; set; }
        public string TablePhoneNo { get; set; }
        public string HouseNo { get; set; }
        public string CityNo { get; set; }
        public string DistrictNo { get; set; }
        public string WardNo { get; set; }
        public string StreetNo { get; set; }
        public string ShipToCityNo { get; set; }
        public string ShipToDistrictNo { get; set; }
        public string ShipToWardNo { get; set; }
        public string ShipToStreetNo { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public System.DateTime DeliveryTimeFrom { get; set; }
        public System.DateTime DeliveryTimeTo { get; set; }
        public string ZoneNo { get; set; }
        public string ShipToAddress { get; set; }
        public string DeliveryComment { get; set; }
        public string BillToName { get; set; }
        public string BillToAddress { get; set; }
        public string VATRegistrationNo { get; set; }
        public string StoreNo { get; set; }
        public string POSTerminalNo { get; set; }
        public string ShiftNo { get; set; }
        public string CashierID { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<double> AmountExclVAT { get; set; }
        public Nullable<double> VATAmount { get; set; }
        public Nullable<double> AmountInclVAT { get; set; }
        public string GeneralComment { get; set; }
        public string UserID { get; set; }
        public Nullable<double> PrepaymentAmount { get; set; }
        public int DeliveringMethod { get; set; }
        public Nullable<double> PaymentAtPOSAmount { get; set; }
        public Nullable<double> InChangeAmount { get; set; }
        public int OrderStatus { get; set; }
        public string ShipToName { get; set; }
        public byte IsTenancy { get; set; }
        public byte InInstalments { get; set; }
        public string ShipToHouseNo { get; set; }
        public string ShipToPhoneNo { get; set; }
        public Nullable<double> AmountDiscountAtPOS { get; set; }
        public byte IssuedVATInvoice { get; set; }
        public string VoucherDiscountNo { get; set; }
        public Nullable<double> VoucherDiscountValue { get; set; }
        public Nullable<double> PointConversionRate { get; set; }
        public string TanencyNo { get; set; }
        public int StepProcess { get; set; }
        public byte SalesIsReturn { get; set; }
        public string MemberCardNo { get; set; }
        public Nullable<double> MemberPoint { get; set; }
        public string ReturnedReceiptNo { get; set; }
        public string ReturnedOrderNo { get; set; }
        public string VATNumber { get; set; }
        public string VATTemplateCode { get; set; }
        public string VATSerial { get; set; }
        public int TransactionType { get; set; }
        public string EventNo { get; set; }
        public int PrintedNumber { get; set; }
        public System.DateTime OrderTime { get; set; }
        public byte IsFullReturn { get; set; }
        public string SendingStatus { get; set; }
        public string BuyerName { get; set; }
        public string BillNumber { get; set; }
        public System.DateTime StartingTime { get; set; }
        public System.DateTime EndingTime { get; set; }
        public string RefKey1 { get; set; }
        public string RefKey2 { get; set; }
        public Nullable<long> Counter { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<bool> IsOfflineVinID { get; set; }
        public Nullable<bool> IsAwardVinID { get; set; }
        public Nullable<double> MemberPointsEarn { get; set; }
        public Nullable<double> MemberPointsRedeem { get; set; }
        public Nullable<bool> IsExtraPoint { get; set; }
        public string VinidCsn { get; set; }
        public string CompanyCodeEmp { get; set; }
        public string DocumentType { get; set; }
        public string UserVoid { get; set; }
        public Nullable<double> MemberPointsRedeemReturned { get; set; }
        public string ReturnVoucherNo { get; set; }
        public string ReturnVoucherExpire { get; set; }
    }
}
