//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.PLHLog
{
    using System;
    using System.Collections.Generic;
    
    public partial class PL_TransactionLoyalty
    {
        public long ID { get; set; }
        public string CardNumber { get; set; }
        public string QRCode { get; set; }
        public string PhoneNumber { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<long> ReferenceNumberCX { get; set; }
        public string TerminalId { get; set; }
        public string StoreID { get; set; }
        public string ChannelCode { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string TransactionType { get; set; }
        public string TransactionName { get; set; }
        public Nullable<double> AmountOnOrderPOS { get; set; }
        public Nullable<double> BillAmount { get; set; }
        public Nullable<double> SpendPoints { get; set; }
        public Nullable<double> RefundAmount { get; set; }
        public string Operator { get; set; }
        public string OrderNo { get; set; }
        public string OrigOrderNo { get; set; }
        public string OrigInvoiceNo { get; set; }
        public Nullable<double> OrigBillAmount { get; set; }
        public string Source { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> NettAmtCX { get; set; }
        public Nullable<double> GrossTransactionAmountCX { get; set; }
        public Nullable<double> AwardPointCX { get; set; }
        public Nullable<double> AwardAmountCX { get; set; }
        public Nullable<double> RedeemPointCX { get; set; }
        public Nullable<double> RedeemAmountCX { get; set; }
        public Nullable<bool> IsOffline { get; set; }
    }
}
