//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.POSBLUE.Infrastructure.Gateways.OneFlexiAxis
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.soap.oneflexi.com", ConfigurationName="VCM.POSBLUE.Infrastructure.Gateways.OneFlexiAxis.OneFlexiAxisServicePortType")]
    public interface OneFlexiAxisServicePortType
    {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:processRequest", ReplyAction="urn:processRequestResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        VCM.POSBLUE.Infrastructure.Gateways.OneFlexiAxis.processRequestResponse processRequest(VCM.POSBLUE.Infrastructure.Gateways.OneFlexiAxis.processRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:processRequest", ReplyAction="urn:processRequestResponse")]
        System.Threading.Tasks.Task<VCM.POSBLUE.Infrastructure.Gateways.OneFlexiAxis.processRequestResponse> processRequestAsync(VCM.POSBLUE.Infrastructure.Gateways.OneFlexiAxis.processRequestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="processRequest", WrapperNamespace="http://service.soap.oneflexi.com", IsWrapped=true)]
    public partial class processRequestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.soap.oneflexi.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string in0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.soap.oneflexi.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string in1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.soap.oneflexi.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string in2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.soap.oneflexi.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string in3;
        
        public processRequestRequest()
        {
        }
        
        public processRequestRequest(string in0, string in1, string in2, string in3)
        {
            this.in0 = in0;
            this.in1 = in1;
            this.in2 = in2;
            this.in3 = in3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="processRequestResponse", WrapperNamespace="http://service.soap.oneflexi.com", IsWrapped=true)]
    public partial class processRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.soap.oneflexi.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public processRequestResponse()
        {
        }
        
        public processRequestResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface OneFlexiAxisServicePortTypeChannel : VCM.POSBLUE.Infrastructure.Gateways.OneFlexiAxis.OneFlexiAxisServicePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class OneFlexiAxisServicePortTypeClient : System.ServiceModel.ClientBase<VCM.POSBLUE.Infrastructure.Gateways.OneFlexiAxis.OneFlexiAxisServicePortType>, VCM.POSBLUE.Infrastructure.Gateways.OneFlexiAxis.OneFlexiAxisServicePortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OneFlexiAxisServicePortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(OneFlexiAxisServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), OneFlexiAxisServicePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OneFlexiAxisServicePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OneFlexiAxisServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OneFlexiAxisServicePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OneFlexiAxisServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OneFlexiAxisServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VCM.POSBLUE.Infrastructure.Gateways.OneFlexiAxis.processRequestResponse VCM.POSBLUE.Infrastructure.Gateways.OneFlexiAxis.OneFlexiAxisServicePortType.processRequest(VCM.POSBLUE.Infrastructure.Gateways.OneFlexiAxis.processRequestRequest request)
        {
            return base.Channel.processRequest(request);
        }
        
        public string processRequest(string in0, string in1, string in2, string in3)
        {
            VCM.POSBLUE.Infrastructure.Gateways.OneFlexiAxis.processRequestRequest inValue = new VCM.POSBLUE.Infrastructure.Gateways.OneFlexiAxis.processRequestRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            inValue.in2 = in2;
            inValue.in3 = in3;
            VCM.POSBLUE.Infrastructure.Gateways.OneFlexiAxis.processRequestResponse retVal = ((VCM.POSBLUE.Infrastructure.Gateways.OneFlexiAxis.OneFlexiAxisServicePortType)(this)).processRequest(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VCM.POSBLUE.Infrastructure.Gateways.OneFlexiAxis.processRequestResponse> VCM.POSBLUE.Infrastructure.Gateways.OneFlexiAxis.OneFlexiAxisServicePortType.processRequestAsync(VCM.POSBLUE.Infrastructure.Gateways.OneFlexiAxis.processRequestRequest request)
        {
            return base.Channel.processRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<VCM.POSBLUE.Infrastructure.Gateways.OneFlexiAxis.processRequestResponse> processRequestAsync(string in0, string in1, string in2, string in3)
        {
            VCM.POSBLUE.Infrastructure.Gateways.OneFlexiAxis.processRequestRequest inValue = new VCM.POSBLUE.Infrastructure.Gateways.OneFlexiAxis.processRequestRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            inValue.in2 = in2;
            inValue.in3 = in3;
            return ((VCM.POSBLUE.Infrastructure.Gateways.OneFlexiAxis.OneFlexiAxisServicePortType)(this)).processRequestAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OneFlexiAxisServiceHttpSoap11Endpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.OneFlexiAxisServiceHttpSoap12Endpoint))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OneFlexiAxisServiceHttpSoap11Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://10.111.55.147:7007/OneFlexiAxisService/services/OneFlexiAxisService.OneFle" +
                        "xiAxisServiceHttpSoap11Endpoint/");
            }
            if ((endpointConfiguration == EndpointConfiguration.OneFlexiAxisServiceHttpSoap12Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://10.111.55.147:7007/OneFlexiAxisService/services/OneFlexiAxisService.OneFle" +
                        "xiAxisServiceHttpSoap12Endpoint/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            OneFlexiAxisServiceHttpSoap11Endpoint,
            
            OneFlexiAxisServiceHttpSoap12Endpoint,
        }
    }
}
