//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUserLoginPOS
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string StaffCode { get; set; }
        public string FullName { get; set; }
        public string StoreNo { get; set; }
        public string PosNo { get; set; }
        public string DeviceName { get; set; }
        public string TypePOS { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
