//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleType
    {
        public byte[] timestamp { get; set; }
        public string Code { get; set; }
        public string PrimaryCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> DefaultFunction { get; set; }
        public Nullable<byte> DefaultCardTender { get; set; }
        public Nullable<byte> DefaultCurrencyTender { get; set; }
        public string Caption { get; set; }
        public Nullable<int> SeqOnPOS { get; set; }
        public Nullable<byte> IsInstallmentSell { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
        public string RefKey1 { get; set; }
        public string RefKey2 { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<long> Counter { get; set; }
        public string Pkey { get; set; }
        public string ChangeTenderCode { get; set; }
        public Nullable<byte> MayBeUsed { get; set; }
        public Nullable<bool> AllowedReturnedOrder { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
