//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssortmentSite
    {
        public int ID { get; set; }
        public string Assortment { get; set; }
        public string StoreNo { get; set; }
        public string Channel { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string IsActive { get; set; }
        public string Pkey { get; set; }
        public Nullable<long> Counter { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
