//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankDiscount
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string StoreGroup { get; set; }
        public string BankCode { get; set; }
        public string TenderType { get; set; }
        public string DiscountType { get; set; }
        public Nullable<double> DiscountValue { get; set; }
        public Nullable<double> MinBillAmount { get; set; }
        public Nullable<double> MaxDiscountAmount { get; set; }
        public Nullable<bool> IsViaTenderType { get; set; }
        public string ViaTenderType { get; set; }
        public Nullable<bool> IsTotalBill { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public string Pkey { get; set; }
        public Nullable<long> Counter { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<bool> IsMember { get; set; }
        public string CustType { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
        public string Ref3 { get; set; }
        public Nullable<bool> IsFullPrice { get; set; }
    }
}
