//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public string No { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string VATRegistrationNo { get; set; }
        public string PhoneNo { get; set; }
        public string FaxNo { get; set; }
        public string BankAccountNo { get; set; }
        public string BankName { get; set; }
        public string BankAddress { get; set; }
        public string BankAcountName { get; set; }
        public string VietnameseDescription { get; set; }
        public string VietnameseAddress { get; set; }
        public string UrlElecInvoice { get; set; }
        public Nullable<long> Counter { get; set; }
        public string Pkey { get; set; }
        public Nullable<bool> IsApplyCashInv { get; set; }
        public Nullable<System.DateTime> FromDateApplyCashInv { get; set; }
    }
}
