//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class BussinessDate
    {
        public string Code { get; set; }
        public string StoreNo { get; set; }
        public string PosTerminal { get; set; }
        public Nullable<System.DateTime> BussinessDate1 { get; set; }
        public Nullable<bool> IsOpened { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<double> BeginAmount { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<double> CloseAmount { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string CreatedUser { get; set; }
        public string UpdatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public byte[] timestamp { get; set; }
    }
}
