//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CentralGeneralContainer : DbContext
    {
        public CentralGeneralContainer()
            : base("name=CentralGeneralContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SQLServer> SQLServers { get; set; }
        public virtual DbSet<StoreSetServer> StoreSetServers { get; set; }
        public virtual DbSet<LogMisSale> LogMisSales { get; set; }
        public virtual DbSet<VatNumber> VatNumbers { get; set; }
        public virtual DbSet<CustomerVAT> CustomerVATs { get; set; }
        public virtual DbSet<InvoiceType> InvoiceTypes { get; set; }
        public virtual DbSet<CheckListDaily> CheckListDailies { get; set; }
        public virtual DbSet<CheckListUser> CheckListUsers { get; set; }
        public virtual DbSet<SERVERWEB> SERVERWEBs { get; set; }
    }
}
