//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class CentralSalesStagingContainer : DbContext
    {
        public static string setDB1 = @"" + ConfigurationManager.AppSettings["setDB1"];
        public static string setDB2 = @"" + ConfigurationManager.AppSettings["setDB2"];
        public CentralSalesStagingContainer()
            : base("name=CentralSalesStagingContainer")
        {
        }
        public CentralSalesStagingContainer(string IPServer)
           : base("name=" + (IPServer == setDB1 ? "SetDB1_CentralSalesStaging"
                          : (IPServer == setDB2 ? "SetDB2_CentralSalesStaging"
                          : "SetDB1_CentralSalesStaging"))
                 )
        {

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<POSBussinessDate_Log> POSBussinessDate_Log { get; set; }
        public virtual DbSet<SyncTableFromPOS> SyncTableFromPOS { get; set; }
        public virtual DbSet<UploadSaleLog> UploadSaleLogs { get; set; }
        public virtual DbSet<TransCpnVchIssue> TransCpnVchIssues { get; set; }
        public virtual DbSet<TransDiscountCouponEntry> TransDiscountCouponEntries { get; set; }
        public virtual DbSet<TransDiscountEntry> TransDiscountEntries { get; set; }
        public virtual DbSet<TransHeader> TransHeaders { get; set; }
        public virtual DbSet<TransInputData> TransInputDatas { get; set; }
        public virtual DbSet<TransLine> TransLines { get; set; }
        public virtual DbSet<TransOptionLine> TransOptionLines { get; set; }
        public virtual DbSet<TransPartnerLine> TransPartnerLines { get; set; }
        public virtual DbSet<TransPaymentEntry> TransPaymentEntries { get; set; }
    }
}
