//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CentralMDPartnerContainer : DbContext
    {
        public CentralMDPartnerContainer()
            : base("name=CentralMDPartnerContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminRole> AdminRoles { get; set; }
        public virtual DbSet<AdminRoleGroup> AdminRoleGroups { get; set; }
        public virtual DbSet<AdminUser> AdminUsers { get; set; }
        public virtual DbSet<AdminUserRole> AdminUserRoles { get; set; }
        public virtual DbSet<AdminUserStore> AdminUserStores { get; set; }
        public virtual DbSet<ArticleType> ArticleTypes { get; set; }
        public virtual DbSet<AssortmentItem> AssortmentItems { get; set; }
        public virtual DbSet<AssortmentSite> AssortmentSites { get; set; }
        public virtual DbSet<AssortmentSiteItem> AssortmentSiteItems { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<BankCardType> BankCardTypes { get; set; }
        public virtual DbSet<BankDiscount> BankDiscounts { get; set; }
        public virtual DbSet<BankDiscountItem> BankDiscountItems { get; set; }
        public virtual DbSet<BankDiscountStore> BankDiscountStores { get; set; }
        public virtual DbSet<Barcode> Barcodes { get; set; }
        public virtual DbSet<BarcodeSetup> BarcodeSetups { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<BSMItemDiscount> BSMItemDiscounts { get; set; }
        public virtual DbSet<ComboRegion> ComboRegions { get; set; }
        public virtual DbSet<ComboStyleProfile> ComboStyleProfiles { get; set; }
        public virtual DbSet<Combox> Comboxes { get; set; }
        public virtual DbSet<CompanyInformation> CompanyInformations { get; set; }
        public virtual DbSet<ConfirmCollectedCash> ConfirmCollectedCashes { get; set; }
        public virtual DbSet<CpnVchBOMCodeIssue> CpnVchBOMCodeIssues { get; set; }
        public virtual DbSet<CpnVchBOMCodeRedeem> CpnVchBOMCodeRedeems { get; set; }
        public virtual DbSet<CpnVchBOMHeader> CpnVchBOMHeaders { get; set; }
        public virtual DbSet<CpnVchBOMIssueRule> CpnVchBOMIssueRules { get; set; }
        public virtual DbSet<CpnVchBOMLine> CpnVchBOMLines { get; set; }
        public virtual DbSet<CpnVchBOMStore> CpnVchBOMStores { get; set; }
        public virtual DbSet<CpnVchCodeSend> CpnVchCodeSends { get; set; }
        public virtual DbSet<CurrencyRate> CurrencyRates { get; set; }
        public virtual DbSet<CXOfflinePercent> CXOfflinePercents { get; set; }
        public virtual DbSet<EDInnovation> EDInnovations { get; set; }
        public virtual DbSet<EDInnovationLine> EDInnovationLines { get; set; }
        public virtual DbSet<EDInnovationSite> EDInnovationSites { get; set; }
        public virtual DbSet<ESL_Item> ESL_Item { get; set; }
        public virtual DbSet<ESL_Item_Price> ESL_Item_Price { get; set; }
        public virtual DbSet<ESL_Store_Change> ESL_Store_Change { get; set; }
        public virtual DbSet<EWalletTerminal> EWalletTerminals { get; set; }
        public virtual DbSet<ExcelExampleCoupon> ExcelExampleCoupons { get; set; }
        public virtual DbSet<ExcelExamplePrice> ExcelExamplePrices { get; set; }
        public virtual DbSet<ExtraFeeHeader> ExtraFeeHeaders { get; set; }
        public virtual DbSet<ExtraFeeLine> ExtraFeeLines { get; set; }
        public virtual DbSet<ExtraFeeOrderType> ExtraFeeOrderTypes { get; set; }
        public virtual DbSet<ExtraFeeStore> ExtraFeeStores { get; set; }
        public virtual DbSet<ExtraFeeStroreGroup> ExtraFeeStroreGroups { get; set; }
        public virtual DbSet<GiftRedeem> GiftRedeems { get; set; }
        public virtual DbSet<GiftRedeemModifyLog> GiftRedeemModifyLogs { get; set; }
        public virtual DbSet<ImageSlider> ImageSliders { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemBlock> ItemBlocks { get; set; }
        public virtual DbSet<ItemBlockVAT> ItemBlockVATs { get; set; }
        public virtual DbSet<ItemDiscount> ItemDiscounts { get; set; }
        public virtual DbSet<ItemDiscountMember> ItemDiscountMembers { get; set; }
        public virtual DbSet<ItemEarnScale> ItemEarnScales { get; set; }
        public virtual DbSet<ItemExtra> ItemExtras { get; set; }
        public virtual DbSet<ItemHiFresh> ItemHiFreshes { get; set; }
        public virtual DbSet<ItemMaxSalesQty> ItemMaxSalesQties { get; set; }
        public virtual DbSet<ItemOption> ItemOptions { get; set; }
        public virtual DbSet<ItemPaymentBlocked> ItemPaymentBlockeds { get; set; }
        public virtual DbSet<ItemPointsMember> ItemPointsMembers { get; set; }
        public virtual DbSet<ItemUnitOfMeasure> ItemUnitOfMeasures { get; set; }
        public virtual DbSet<JobRunning> JobRunnings { get; set; }
        public virtual DbSet<KafkaReport> KafkaReports { get; set; }
        public virtual DbSet<LinkedItem> LinkedItems { get; set; }
        public virtual DbSet<LogErrorWeb> LogErrorWebs { get; set; }
        public virtual DbSet<LogSendEmail> LogSendEmails { get; set; }
        public virtual DbSet<LoyaltyRate> LoyaltyRates { get; set; }
        public virtual DbSet<MappingQRCode> MappingQRCodes { get; set; }
        public virtual DbSet<Marketing> Marketings { get; set; }
        public virtual DbSet<MCH> MCHes { get; set; }
        public virtual DbSet<MemberBalance> MemberBalances { get; set; }
        public virtual DbSet<MemberEarnItem> MemberEarnItems { get; set; }
        public virtual DbSet<MemberEarnItemLog> MemberEarnItemLogs { get; set; }
        public virtual DbSet<MemberEarnTransaction> MemberEarnTransactions { get; set; }
        public virtual DbSet<MemberEarnTransactionLine> MemberEarnTransactionLines { get; set; }
        public virtual DbSet<MemberTransaction> MemberTransactions { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<MenuRole> MenuRoles { get; set; }
        public virtual DbSet<MMLItemDiscount> MMLItemDiscounts { get; set; }
        public virtual DbSet<MMLSchemeHeader> MMLSchemeHeaders { get; set; }
        public virtual DbSet<MMLSchemeItem> MMLSchemeItems { get; set; }
        public virtual DbSet<MMLSchemeResponse> MMLSchemeResponses { get; set; }
        public virtual DbSet<Notify> Notifies { get; set; }
        public virtual DbSet<NotifyComfirm> NotifyComfirms { get; set; }
        public virtual DbSet<NotifyConfig> NotifyConfigs { get; set; }
        public virtual DbSet<NotifyTelegram> NotifyTelegrams { get; set; }
        public virtual DbSet<Odoo_SALE> Odoo_SALE { get; set; }
        public virtual DbSet<OfferBenefit> OfferBenefits { get; set; }
        public virtual DbSet<OfferBuy> OfferBuys { get; set; }
        public virtual DbSet<OfferGet> OfferGets { get; set; }
        public virtual DbSet<OfferHeader> OfferHeaders { get; set; }
        public virtual DbSet<OfferMaxQuantity> OfferMaxQuantities { get; set; }
        public virtual DbSet<OfferPriority> OfferPriorities { get; set; }
        public virtual DbSet<OfferRetrict> OfferRetricts { get; set; }
        public virtual DbSet<OfferSite> OfferSites { get; set; }
        public virtual DbSet<OfferType> OfferTypes { get; set; }
        public virtual DbSet<OptionData> OptionDatas { get; set; }
        public virtual DbSet<OptionDataPartner> OptionDataPartners { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<PartnerEarnPointBlocked> PartnerEarnPointBlockeds { get; set; }
        public virtual DbSet<PartnerPaymentBlocked> PartnerPaymentBlockeds { get; set; }
        public virtual DbSet<PartnerService> PartnerServices { get; set; }
        public virtual DbSet<PartnerServiceItem> PartnerServiceItems { get; set; }
        public virtual DbSet<PartnerSetup> PartnerSetups { get; set; }
        public virtual DbSet<PaymentMethodQRCode> PaymentMethodQRCodes { get; set; }
        public virtual DbSet<POSDataSetup> POSDataSetups { get; set; }
        public virtual DbSet<PosGroup> PosGroups { get; set; }
        public virtual DbSet<PosGroupItem> PosGroupItems { get; set; }
        public virtual DbSet<POSHotKeyGroup> POSHotKeyGroups { get; set; }
        public virtual DbSet<POSHotKeyItem> POSHotKeyItems { get; set; }
        public virtual DbSet<POSHotKeyItemGroup> POSHotKeyItemGroups { get; set; }
        public virtual DbSet<POSInfo> POSInfoes { get; set; }
        public virtual DbSet<POSMonitor> POSMonitors { get; set; }
        public virtual DbSet<POSTerminal> POSTerminals { get; set; }
        public virtual DbSet<POSTerminalBank> POSTerminalBanks { get; set; }
        public virtual DbSet<PosterminalMapping> PosterminalMappings { get; set; }
        public virtual DbSet<POSTerminalSetup> POSTerminalSetups { get; set; }
        public virtual DbSet<PosUpdateLog> PosUpdateLogs { get; set; }
        public virtual DbSet<POSVATCode> POSVATCodes { get; set; }
        public virtual DbSet<POSVersion> POSVersions { get; set; }
        public virtual DbSet<PosWebGroup> PosWebGroups { get; set; }
        public virtual DbSet<PosWebGroupItem> PosWebGroupItems { get; set; }
        public virtual DbSet<Price_Range> Price_Range { get; set; }
        public virtual DbSet<PriceGroup> PriceGroups { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<ReasonCode> ReasonCodes { get; set; }
        public virtual DbSet<RetailSetup> RetailSetups { get; set; }
        public virtual DbSet<RewardCode> RewardCodes { get; set; }
        public virtual DbSet<RewardCodeSend> RewardCodeSends { get; set; }
        public virtual DbSet<RewardHeader> RewardHeaders { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SalesOrderType> SalesOrderTypes { get; set; }
        public virtual DbSet<SalesOrderTypeByStore> SalesOrderTypeByStores { get; set; }
        public virtual DbSet<SalesPrice> SalesPrices { get; set; }
        public virtual DbSet<SalesPriceRange> SalesPriceRanges { get; set; }
        public virtual DbSet<SalesPriceRate> SalesPriceRates { get; set; }
        public virtual DbSet<SetupGroupItem> SetupGroupItems { get; set; }
        public virtual DbSet<SetupGroupSite> SetupGroupSites { get; set; }
        public virtual DbSet<SetupItemLineItem> SetupItemLineItems { get; set; }
        public virtual DbSet<SetupPromotionBUY> SetupPromotionBUYs { get; set; }
        public virtual DbSet<SetupPromotionGET> SetupPromotionGETs { get; set; }
        public virtual DbSet<SetupPromotionHEADER> SetupPromotionHEADERs { get; set; }
        public virtual DbSet<SetupPromotionSITE> SetupPromotionSITEs { get; set; }
        public virtual DbSet<SetupSalePriceLineItem> SetupSalePriceLineItems { get; set; }
        public virtual DbSet<SetupSiteCustomerMaster> SetupSiteCustomerMasters { get; set; }
        public virtual DbSet<SignalStore> SignalStores { get; set; }
        public virtual DbSet<SmartPOS> SmartPOS { get; set; }
        public virtual DbSet<SourceBill> SourceBills { get; set; }
        public virtual DbSet<SpecialComboHeader> SpecialComboHeaders { get; set; }
        public virtual DbSet<SpecialComboLine> SpecialComboLines { get; set; }
        public virtual DbSet<SpecialComboStore> SpecialComboStores { get; set; }
        public virtual DbSet<StackTraceLog> StackTraceLogs { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<StoreGroup> StoreGroups { get; set; }
        public virtual DbSet<StoreNoMapping> StoreNoMappings { get; set; }
        public virtual DbSet<StorePriceGroup> StorePriceGroups { get; set; }
        public virtual DbSet<StoreSetup> StoreSetups { get; set; }
        public virtual DbSet<SurveyAnswer> SurveyAnswers { get; set; }
        public virtual DbSet<SurveyQuestion> SurveyQuestions { get; set; }
        public virtual DbSet<SyncAction> SyncActions { get; set; }
        public virtual DbSet<SyncActionFinished> SyncActionFinisheds { get; set; }
        public virtual DbSet<SyncChangeLog> SyncChangeLogs { get; set; }
        public virtual DbSet<SyncChangeLogStore> SyncChangeLogStores { get; set; }
        public virtual DbSet<SyncChangeLogStore_Web> SyncChangeLogStore_Web { get; set; }
        public virtual DbSet<SyncCopyFileLog> SyncCopyFileLogs { get; set; }
        public virtual DbSet<SyncDataAll> SyncDataAlls { get; set; }
        public virtual DbSet<SyncDateLog> SyncDateLogs { get; set; }
        public virtual DbSet<SyncJobLog> SyncJobLogs { get; set; }
        public virtual DbSet<SyncJobLogCounter> SyncJobLogCounters { get; set; }
        public virtual DbSet<SyncJobPOSLog> SyncJobPOSLogs { get; set; }
        public virtual DbSet<SyncStoreChangeList> SyncStoreChangeLists { get; set; }
        public virtual DbSet<SyncStoreChangeListLog> SyncStoreChangeListLogs { get; set; }
        public virtual DbSet<SyncTableFromPOS> SyncTableFromPOS { get; set; }
        public virtual DbSet<SyncTableList> SyncTableLists { get; set; }
        public virtual DbSet<SyncWriteFileLog> SyncWriteFileLogs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<SysWebApi> SysWebApis { get; set; }
        public virtual DbSet<SysWebApiConfig> SysWebApiConfigs { get; set; }
        public virtual DbSet<SysWebApiRoute> SysWebApiRoutes { get; set; }
        public virtual DbSet<SysWebApiUser> SysWebApiUsers { get; set; }
        public virtual DbSet<TenderType> TenderTypes { get; set; }
        public virtual DbSet<TenderTypeConfig> TenderTypeConfigs { get; set; }
        public virtual DbSet<TenderTypeImage> TenderTypeImages { get; set; }
        public virtual DbSet<TenderTypeSetup> TenderTypeSetups { get; set; }
        public virtual DbSet<UnitOfMeasure> UnitOfMeasures { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VinIDOfflinePercent> VinIDOfflinePercents { get; set; }
        public virtual DbSet<VoucherPartner> VoucherPartners { get; set; }
        public virtual DbSet<VoucherType> VoucherTypes { get; set; }
        public virtual DbSet<WeightScale_AssortmentItem> WeightScale_AssortmentItem { get; set; }
        public virtual DbSet<WeightScale_AssortmentSite> WeightScale_AssortmentSite { get; set; }
        public virtual DbSet<WeightScale_INGREDIENT> WeightScale_INGREDIENT { get; set; }
        public virtual DbSet<WeightScale_Item_Change> WeightScale_Item_Change { get; set; }
        public virtual DbSet<WeightScale_Log> WeightScale_Log { get; set; }
        public virtual DbSet<WeightScale_Multimex> WeightScale_Multimex { get; set; }
        public virtual DbSet<WeightScale_PLU_LIST> WeightScale_PLU_LIST { get; set; }
        public virtual DbSet<WeightScale_PLU_PRICE_STORE> WeightScale_PLU_PRICE_STORE { get; set; }
        public virtual DbSet<WeightScale_Processing> WeightScale_Processing { get; set; }
        public virtual DbSet<WinCodeCustomer> WinCodeCustomers { get; set; }
        public virtual DbSet<WinCodeHeader> WinCodeHeaders { get; set; }
        public virtual DbSet<WinCodeStore> WinCodeStores { get; set; }
        public virtual DbSet<CpnVchBOMQuota> CpnVchBOMQuotas { get; set; }
        public virtual DbSet<Interface_Errors> Interface_Errors { get; set; }
    }
}
