//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CentralSalesContainer : DbContext
    {
        public static string setDB1 = @"" + ConfigurationManager.AppSettings["setDB1"];
        public static string setDB2 = @"" + ConfigurationManager.AppSettings["setDB2"];
        public CentralSalesContainer()
            : base("name=CentralSalesContainer")
        {
        }
        public CentralSalesContainer(string IPServer)
           : base("name=" + (IPServer == setDB1 ? "SetDB1_CentralSale"
                          : (IPServer == setDB2 ? "SetDB2_CentralSale"
                          : "SetDB1_CentralSale"))
                 )
        {

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TransBluePoint> TransBluePoints { get; set; }
        public virtual DbSet<TransDiscountCouponEntry> TransDiscountCouponEntries { get; set; }
        public virtual DbSet<TransInfocodeEntry> TransInfocodeEntries { get; set; }
        public virtual DbSet<TransLine> TransLines { get; set; }
        public virtual DbSet<TransPartnerLine> TransPartnerLines { get; set; }
        public virtual DbSet<TransPaymentEntry> TransPaymentEntries { get; set; }
        public virtual DbSet<TransVoidHeader> TransVoidHeaders { get; set; }
        public virtual DbSet<ShiftHeader> ShiftHeaders { get; set; }
        public virtual DbSet<BussinessDate> BussinessDates { get; set; }
        public virtual DbSet<BussinessDateConfirm> BussinessDateConfirms { get; set; }
        public virtual DbSet<BussinessDateOpen> BussinessDateOpens { get; set; }
        public virtual DbSet<ShiftOrder> ShiftOrders { get; set; }
        public virtual DbSet<POSEOD> POSEODs { get; set; }
        public virtual DbSet<FinishSale> FinishSales { get; set; }
        public virtual DbSet<ShiftLine> ShiftLines { get; set; }
        public virtual DbSet<ShiftHeaderDescription> ShiftHeaderDescriptions { get; set; }
        public virtual DbSet<TransHeader> TransHeaders { get; set; }
        public virtual DbSet<TransCpnVchIssue> TransCpnVchIssues { get; set; }
        public virtual DbSet<TransDiscountEntry> TransDiscountEntries { get; set; }
        public virtual DbSet<TransVoidLine> TransVoidLines { get; set; }
    }
}
