//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckListDaily
    {
        public int ID { get; set; }
        public string CheckListName { get; set; }
        public string TimeCheck { get; set; }
        public string OwnerCheck { get; set; }
        public string Note { get; set; }
    }
}
