//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfirmCollectedCash
    {
        public string BussinessDate { get; set; }
        public string StoreCode { get; set; }
        public string PosCode { get; set; }
        public string StaffID { get; set; }
        public string ShiftNumber { get; set; }
        public string WincareBarcode { get; set; }
        public string StoreCodeWin { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public int TotalCash { get; set; }
        public System.DateTime CrtDate { get; set; }
        public string BillCode { get; set; }
        public string SourceData { get; set; }
    }
}
