//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class CpnVchBOMQuota
    {
        public string ItemNo { get; set; }
        public string UnitOfMeasure { get; set; }
        public bool IsCheckMember { get; set; }
        public int LimitQty { get; set; }
        public bool Blocked { get; set; }
        public int QtyOfDay { get; set; }
    
        public virtual CpnVchBOMHeader CpnVchBOMHeader { get; set; }
    }
}
