//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class CpnVchBOMCodeIssue
    {
        public long ID { get; set; }
        public string ItemNo { get; set; }
        public string Code { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> Counter { get; set; }
        public string Pkey { get; set; }
    }
}
