//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class CpnVchBOMLine
    {
        public string ItemNo { get; set; }
        public int LineNo { get; set; }
        public string LineItemNo { get; set; }
        public string Description { get; set; }
        public string UnitOfMeasure { get; set; }
        public Nullable<long> Counter { get; set; }
        public string Barcode { get; set; }
        public string Pkey { get; set; }
    }
}
