//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class EWalletTerminal
    {
        public string PartnerId { get; set; }
        public string TerminalCode { get; set; }
        public string EWalletCode { get; set; }
        public string EWalletName { get; set; }
        public string StoreNoFull { get; set; }
        public string StoreNo { get; set; }
        public string POSNo { get; set; }
        public string AccessKey { get; set; }
        public string PaymentType { get; set; }
        public string TenderType { get; set; }
        public string POSTerminal { get; set; }
        public Nullable<bool> IsTPay { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<long> Counter { get; set; }
        public string Pkey { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedUser { get; set; }
        public byte[] timestamp { get; set; }
        public string Mode { get; set; }
    }
}
