//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraFeeLine
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string ItemType { get; set; }
        public string No { get; set; }
        public Nullable<double> ExtraFeeValue { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public string PKey { get; set; }
        public Nullable<long> Counter { get; set; }
    }
}
