//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class INBOUNDContainer : DbContext
    {
        public INBOUNDContainer()
            : base("name=INBOUNDContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OCC_TransHeader> OCC_TransHeader { get; set; }
        public virtual DbSet<OCC_TransLine> OCC_TransLine { get; set; }
        public virtual DbSet<OCC_TransPaymentEntry> OCC_TransPaymentEntry { get; set; }
    }
}
