//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPointsMember
    {
        public string PointsCode { get; set; }
        public string ItemNo { get; set; }
        public string Barcode { get; set; }
        public string ItemName { get; set; }
        public string Uom { get; set; }
        public int ShelfLife { get; set; }
        public bool Blocked { get; set; }
        public System.DateTime CrtDate { get; set; }
        public int DaysOfUsed { get; set; }
    }
}
