//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemOption
    {
        public int Id { get; set; }
        public string ItemNo { get; set; }
        public string ItemNoOption { get; set; }
        public string OptionType { get; set; }
        public string OptionName { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<long> Counter { get; set; }
        public string Pkey { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<System.DateTime> LastDateModified { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<int> Seq { get; set; }
    }
}
