//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public string No { get; set; }
        public string No2 { get; set; }
        public string Description { get; set; }
        public string SearchDescription { get; set; }
        public string LongDescription { get; set; }
        public string BaseUnitOfMeasure { get; set; }
        public int StatisticsGroup { get; set; }
        public int CommissionGroup { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public int CostingMethod { get; set; }
        public Nullable<double> UnitCost { get; set; }
        public Nullable<double> StandardCost { get; set; }
        public string VendorNo { get; set; }
        public string VendorItemNo { get; set; }
        public Nullable<double> MaximumInventory { get; set; }
        public Nullable<double> ReorderQuantity { get; set; }
        public Nullable<double> GrossWeight { get; set; }
        public Nullable<double> NetWeight { get; set; }
        public Nullable<double> UnitsPerParcel { get; set; }
        public Nullable<double> UnitVolume { get; set; }
        public byte Blocked { get; set; }
        public System.DateTime LastDateModified { get; set; }
        public byte PriceIncludesVAT { get; set; }
        public string TaxGroupCode { get; set; }
        public int PreventNegativeInventory { get; set; }
        public Nullable<double> MinimumOrderQuantity { get; set; }
        public Nullable<double> MaximumOrderQuantity { get; set; }
        public Nullable<double> SafetyStockQuantity { get; set; }
        public Nullable<double> OrderMultiple { get; set; }
        public string SalesUnitOfMeasure { get; set; }
        public string ManufacturerCode { get; set; }
        public string ItemCategoryCode { get; set; }
        public string ProductGroupCode { get; set; }
        public string ServiceItemGroup { get; set; }
        public string ItemTrackingCode { get; set; }
        public string ProductionBOMNo { get; set; }
        public byte BlockedVINID { get; set; }
        public string CommonItemNo { get; set; }
        public string ItemFamilyCode { get; set; }
        public string DivisionCode { get; set; }
        public byte KeyinginPrice { get; set; }
        public byte ZeroPriceValid { get; set; }
        public Nullable<long> Counter { get; set; }
        public string Pkey { get; set; }
        public string ParentCode { get; set; }
        public string Size { get; set; }
        public string ImageName { get; set; }
        public Nullable<bool> IsVAT { get; set; }
        public string WeightscaleDesc { get; set; }
    }
}
