//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemDiscount
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public string StoreNo { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Description { get; set; }
        public string ItemNo { get; set; }
        public string UOM { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<bool> IsGenerateBarcode { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Seq { get; set; }
        public Nullable<long> Counter { get; set; }
        public string Pkey { get; set; }
        public Nullable<System.DateTime> LastDateModified { get; set; }
        public string LastUserModified { get; set; }
        public string WinCode { get; set; }
        public Nullable<double> MinAmount { get; set; }
        public string DiscountBy { get; set; }
        public string PromotionCode { get; set; }
        public string PromotionItem { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
        public string Ref3 { get; set; }
        public string Ref4 { get; set; }
        public string Ref5 { get; set; }
    }
}
