//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class KafkaReport
    {
        public string OrderDate { get; set; }
        public string BootstrapServers { get; set; }
        public string Topic { get; set; }
        public string GroupId { get; set; }
        public string Partition { get; set; }
        public long MinOffset { get; set; }
        public long MaxOffset { get; set; }
        public long CommittedOffset { get; set; }
        public System.DateTime CrtDate { get; set; }
    }
}
