//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkedItem
    {
        public string ItemNo { get; set; }
        public string UnitOfMeasure { get; set; }
        public string LinkedItemNo { get; set; }
        public decimal NoOfItems { get; set; }
        public byte Blocked { get; set; }
        public string PrimaryKey { get; set; }
        public string SalesType { get; set; }
        public byte DepositItem { get; set; }
        public Nullable<long> Counter { get; set; }
        public string Pkey { get; set; }
    }
}
