//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogErrorWeb
    {
        public long ID { get; set; }
        public string StoreNo { get; set; }
        public string PosTerminal { get; set; }
        public string OrderNo { get; set; }
        public string Action { get; set; }
        public string Description { get; set; }
        public string Msg { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
