//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogSendEmail
    {
        public int ID { get; set; }
        public string PKey { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string DataType { get; set; }
        public Nullable<int> NumberOfSend { get; set; }
    }
}
