//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marketing
    {
        public long ID { get; set; }
        public string POSTerminal { get; set; }
        public string StoreNo { get; set; }
        public string QRLink { get; set; }
        public string Content { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ContentType { get; set; }
        public Nullable<double> FromAmount { get; set; }
        public Nullable<double> ToAmount { get; set; }
        public Nullable<bool> IsDynamicURL { get; set; }
        public Nullable<bool> IsCheckSum { get; set; }
        public Nullable<int> CheckSumPosition { get; set; }
        public Nullable<bool> IsEncryptCheckSum { get; set; }
        public Nullable<long> Counter { get; set; }
        public string Pkey { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> RetrictPaymentMethod { get; set; }
    }
}
