//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberEarnItem
    {
        public string ItemNo { get; set; }
        public string Uom { get; set; }
        public string Size { get; set; }
        public int SaleQty { get; set; }
        public int StampsQty { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public bool Blocked { get; set; }
        public string CrtUser { get; set; }
        public System.DateTime CrtdDate { get; set; }
        public System.DateTime UpdDate { get; set; }
    }
}
