//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberEarnTransaction
    {
        public string MemberCard { get; set; }
        public string OrderNo { get; set; }
        public string StoreNo { get; set; }
        public string PosNo { get; set; }
        public System.DateTime BusinessDate { get; set; }
        public string TransType { get; set; }
        public int Quantity { get; set; }
        public string ReturnedOrderNo { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
