//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberTransaction
    {
        public string StoreNo { get; set; }
        public string PosNo { get; set; }
        public Nullable<System.DateTime> BusinessDate { get; set; }
        public string MemberCard { get; set; }
        public string TransType { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public System.Guid ID { get; set; }
    }
}
