//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class MMLItemDiscount
    {
        public long Id { get; set; }
        public string StoreNo { get; set; }
        public string Description { get; set; }
        public string ItemNo { get; set; }
        public string UOM { get; set; }
        public Nullable<double> DiscountPrice { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string FromTime { get; set; }
        public string ToTime { get; set; }
        public string BonusBuyCode { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<long> Counter { get; set; }
        public string Pkey { get; set; }
        public Nullable<System.DateTime> LastDateModified { get; set; }
        public string LastUserModified { get; set; }
        public string RefID { get; set; }
        public Nullable<System.DateTime> RefModifiedDate { get; set; }
        public Nullable<double> MBSDiscountPrice { get; set; }
        public Nullable<int> DiscountType { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
        public string Ref3 { get; set; }
        public string Ref4 { get; set; }
        public string Ref5 { get; set; }
    }
}
