//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotifyConfig
    {
        public string AppCode { get; set; }
        public string ActionType { get; set; }
        public string Status { get; set; }
        public string Message { get; set; }
        public string MessageFormat { get; set; }
        public bool Blocked { get; set; }
        public bool IsOffline { get; set; }
    }
}
