//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotifyTelegram
    {
        public string GroupId { get; set; }
        public int Priority { get; set; }
        public string WebApi { get; set; }
        public string Auth { get; set; }
        public string Desc { get; set; }
        public bool Blocked { get; set; }
        public string Notify { get; set; }
    }
}
