//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCC_TransLine
    {
        public string OrderNo { get; set; }
        public int LineType { get; set; }
        public int LineNo { get; set; }
        public int LineNo2 { get; set; }
        public int ParentLineNo { get; set; }
        public string ItemNo { get; set; }
        public string ItemNo2 { get; set; }
        public string ItemName { get; set; }
        public string Uom { get; set; }
        public decimal Quantity { get; set; }
        public decimal OriginPrice { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal NetPrice { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal VATPercent { get; set; }
        public decimal VATAmount { get; set; }
        public decimal LineAmountExcVAT { get; set; }
        public decimal LineAmountIncVAT { get; set; }
        public decimal OriginLineAmountIncVAT { get; set; }
        public decimal RevenueShareRatio { get; set; }
        public string VATGroup { get; set; }
        public decimal MemberPointsEarn { get; set; }
        public decimal MemberPointsRedeem { get; set; }
        public string CupType { get; set; }
        public string Size { get; set; }
        public bool IsTopping { get; set; }
        public bool IsCombo { get; set; }
        public System.DateTime ScanTime { get; set; }
        public string UpdateFlg { get; set; }
        public System.DateTime CrtDate { get; set; }
        public decimal CommissionsAmount { get; set; }
    }
}
