//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCC_TransPaymentEntry
    {
        public string OrderNo { get; set; }
        public int LineNo { get; set; }
        public string StoreNo { get; set; }
        public string PosNo { get; set; }
        public string TenderType { get; set; }
        public string CurrencyCode { get; set; }
        public decimal ExchangeRate { get; set; }
        public decimal AmountTendered { get; set; }
        public decimal AmountInCurrency { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string ReferenceNo { get; set; }
    }
}
