//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCC_TransHeader
    {
        public string AppCode { get; set; }
        public string Version { get; set; }
        public string OrderNo { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string StoreNo { get; set; }
        public string StoreNo2 { get; set; }
        public string PosNo { get; set; }
        public string OrderType { get; set; }
        public string TransactionType { get; set; }
        public string BeginDate { get; set; }
        public string EndDate { get; set; }
        public string TransactionCurrency { get; set; }
        public string MemberCardNo { get; set; }
        public decimal MemberPointsEarn { get; set; }
        public decimal MemberPointsRedeem { get; set; }
        public string RefKey { get; set; }
        public bool IssuedVATInvoice { get; set; }
        public string UpdateFlg { get; set; }
        public bool IsEOD { get; set; }
        public System.DateTime CrtDate { get; set; }
        public string OrderNo2 { get; set; }
    }
}
