//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odoo_SALE
    {
        public long ID { get; set; }
        public string OrderNo { get; set; }
        public string ItemNo { get; set; }
        public string BarcodeNo { get; set; }
        public string UOM { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<bool> Status { get; set; }
        public string StoreNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
