//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferSite
    {
        public string OfferNo { get; set; }
        public string PriceGroupCode { get; set; }
        public string StoreNo { get; set; }
        public Nullable<long> Counter { get; set; }
        public string Pkey { get; set; }
    }
}
