//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferType
    {
        public int ID { get; set; }
        public string OfferType1 { get; set; }
        public string OfferName { get; set; }
        public Nullable<bool> IsTotalBill { get; set; }
        public Nullable<bool> IsSetupBuy { get; set; }
        public Nullable<bool> IsSetupGet { get; set; }
        public Nullable<bool> IsVoucher { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsGift { get; set; }
        public string Description { get; set; }
        public string UserGuide { get; set; }
    }
}
