//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferMaxQuantity
    {
        public int ID { get; set; }
        public string OfferNo { get; set; }
        public string StoreNo { get; set; }
        public string ItemNo { get; set; }
        public string UOM { get; set; }
        public Nullable<double> MaxQuantity { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedUser { get; set; }
        public Nullable<System.DateTime> RefUpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<double> QuantitySale { get; set; }
        public Nullable<bool> IsRetricted { get; set; }
    }
}
