//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferHeader
    {
        public string No { get; set; }
        public int Type { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public string OfferType { get; set; }
        public string PriceGroup { get; set; }
        public string RoundingMethod { get; set; }
        public string CurrencyCode { get; set; }
        public System.DateTime LastDateModified { get; set; }
        public string ValidationPeriodID { get; set; }
        public string ValidationDescription { get; set; }
        public System.DateTime StartingDate { get; set; }
        public System.DateTime EndingDate { get; set; }
        public byte BlockPeriodicDiscount { get; set; }
        public Nullable<double> DealPrice { get; set; }
        public int ShowDealLines { get; set; }
        public string SalesTypeFilter { get; set; }
        public int SelectionType { get; set; }
        public string CustomerDiscGroup { get; set; }
        public string MemberValue { get; set; }
        public string DiscountTrackingNo { get; set; }
        public string CouponCode { get; set; }
        public Nullable<double> CouponQtyNeeded { get; set; }
        public int MemberType { get; set; }
        public string MemberAttribute { get; set; }
        public string MemberAttributeValue { get; set; }
        public byte BlockSalesCommission { get; set; }
        public byte BlockManualPriceChange { get; set; }
        public byte BlockInfoCodeDiscount { get; set; }
        public byte BlockLineDiscountOffer { get; set; }
        public byte BlockTotalDiscountOffer { get; set; }
        public byte BlockTenderTypeDiscount { get; set; }
        public byte BlockMemberPoints { get; set; }
        public int ConditionBuy { get; set; }
        public byte MemberOnly { get; set; }
        public int ConditionGet { get; set; }
        public string NoSeries { get; set; }
        public string FromTime { get; set; }
        public string ToTime { get; set; }
        public byte Mon { get; set; }
        public byte Tue { get; set; }
        public byte Wed { get; set; }
        public byte Thu { get; set; }
        public byte Fri { get; set; }
        public byte Sat { get; set; }
        public byte Sun { get; set; }
        public int NumOfDays { get; set; }
        public string DayOfWeek { get; set; }
        public string TenderTypeCode { get; set; }
        public Nullable<double> TenderTypeValue { get; set; }
        public Nullable<double> TenderTypeOfferPercent { get; set; }
        public Nullable<double> TenderTypeOfferAmount { get; set; }
        public string BankCode { get; set; }
        public string LocalSiteGroup { get; set; }
        public Nullable<double> LimitQty { get; set; }
        public Nullable<System.DateTime> VoucherFromDate { get; set; }
        public Nullable<System.DateTime> VoucherToDate { get; set; }
        public Nullable<int> VoucherValidDay { get; set; }
        public Nullable<int> VoucherLimitNumber { get; set; }
        public string PromotionNo { get; set; }
        public Nullable<int> PriorityBBY { get; set; }
        public Nullable<long> Counter { get; set; }
        public string Pkey { get; set; }
        public Nullable<double> MinValue { get; set; }
        public Nullable<int> TotalDiscountType { get; set; }
        public Nullable<double> TotalDiscountValue { get; set; }
        public Nullable<bool> IsVoucher { get; set; }
        public Nullable<bool> IsTotalBill { get; set; }
        public Nullable<bool> IsGift { get; set; }
        public string MemberCode { get; set; }
        public Nullable<double> DiscountAmountMax { get; set; }
        public Nullable<bool> IsFullPrice { get; set; }
        public string Remark { get; set; }
        public string SalesType { get; set; }
    }
}
