//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferGet
    {
        public string OfferNo { get; set; }
        public int LineNo { get; set; }
        public int LineType { get; set; }
        public string No { get; set; }
        public string Description { get; set; }
        public string UnitOfMeasure { get; set; }
        public int DiscountType { get; set; }
        public Nullable<double> DiscountValue { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Step { get; set; }
        public string BonusBuyNo { get; set; }
        public string LineGroup { get; set; }
        public string ScaleType { get; set; }
        public Nullable<long> Counter { get; set; }
        public string Pkey { get; set; }
    }
}
