//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionData
    {
        public byte[] timestamp { get; set; }
        public string Code { get; set; }
        public string PrimaryCode { get; set; }
        public string Description { get; set; }
        public string TenderType { get; set; }
        public string TenderTypeName { get; set; }
        public string PaymentType { get; set; }
        public string PaymentTypeName { get; set; }
        public string SalesType { get; set; }
        public string SalesTypeName { get; set; }
        public string Caption { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<bool> AllowedReturnedOrder { get; set; }
        public Nullable<bool> IsTPay { get; set; }
        public Nullable<byte> MayBeUsed { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<int> SeqOnPOS { get; set; }
        public string HotKey { get; set; }
        public Nullable<long> Counter { get; set; }
        public string Pkey { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    }
}
