//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerSetup
    {
        public long ID { get; set; }
        public string StoreNo { get; set; }
        public string PartnerCode { get; set; }
        public string PartnerName { get; set; }
        public string ServiceCode { get; set; }
        public string ServiceName { get; set; }
        public string DefaultItemNo { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<bool> IsDynamicLogic { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Order { get; set; }
        public string HotKey { get; set; }
        public Nullable<int> Counter { get; set; }
        public string Pkey { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    }
}
