//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PLHWebMobileContainer : DbContext
    {
        public PLHWebMobileContainer()
            : base("name=PLHWebMobileContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminUserLoginPOS> AdminUserLoginPOS { get; set; }
        public virtual DbSet<StoreSetupPrint> StoreSetupPrints { get; set; }
        public virtual DbSet<AdminUser> AdminUsers { get; set; }
    }
}
