//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSInfo
    {
        public string IPAddress { get; set; }
        public string POSID { get; set; }
        public string StoreNo { get; set; }
        public Nullable<int> Counter { get; set; }
        public string PKey { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
