//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSMonitor
    {
        public int ID { get; set; }
        public string StoreNo { get; set; }
        public string IpAddress { get; set; }
        public string ComputerName { get; set; }
        public string PosTerminalID { get; set; }
        public string BluePosVersion { get; set; }
        public Nullable<System.DateTime> BluePosVersionUpdate { get; set; }
        public Nullable<short> BluePosDatabaseStatus { get; set; }
        public string JobVersion { get; set; }
        public string ScriptVersion { get; set; }
        public Nullable<bool> IsOpenBluePos { get; set; }
        public Nullable<System.DateTime> DateTimePos { get; set; }
        public Nullable<System.DateTime> FirstTimeEvent { get; set; }
        public Nullable<System.DateTime> LastTimeEvent { get; set; }
        public Nullable<bool> IsMonitor { get; set; }
        public Nullable<int> IntervalJob { get; set; }
        public Nullable<System.DateTime> LastTimeInsertAll { get; set; }
        public Nullable<System.DateTime> LastTimeInsertChange { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
