//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTerminalBank
    {
        public string BankPOSCode { get; set; }
        public string BankPOSName { get; set; }
        public string BankCode { get; set; }
        public string StoreNoFull { get; set; }
        public string StoreNo { get; set; }
        public string POSNo { get; set; }
        public string AccessKey { get; set; }
        public Nullable<bool> IsOnline { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<long> Counter { get; set; }
        public string Pkey { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedUser { get; set; }
        public string POSTerminal { get; set; }
        public string PartnerId { get; set; }
    }
}
