//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTerminal
    {
        public string MACAddress { get; set; }
        public string IPAddress { get; set; }
        public string No { get; set; }
        public string StoreNo { get; set; }
        public Nullable<int> TerminalType { get; set; }
        public string Description { get; set; }
        public string Placement { get; set; }
        public Nullable<int> StatementMethod { get; set; }
        public Nullable<byte> TerminalStatement { get; set; }
        public string DefaultPriceGroup { get; set; }
        public string TerminalNetworkID { get; set; }
        public string TerminalIPAddress { get; set; }
        public Nullable<int> TerminalConnection { get; set; }
        public Nullable<byte> ShowItemPictures { get; set; }
        public Nullable<byte> ShowItemHtml { get; set; }
        public Nullable<byte> DisplayTerminalClosed { get; set; }
        public Nullable<byte> DisplayLinkedItem { get; set; }
        public Nullable<int> AutoLogoffAfter_Min { get; set; }
        public Nullable<byte> ReturnInTransaction { get; set; }
        public Nullable<int> ItemNoOnReceipt { get; set; }
        public Nullable<System.DateTime> LastDateModified { get; set; }
        public string PrintReceiptLogo { get; set; }
        public Nullable<int> PrintReceiptBitmapNo { get; set; }
        public Nullable<int> RcptTextMaxLength { get; set; }
        public Nullable<byte> ReceiptBarcode { get; set; }
        public Nullable<int> ReceiptSetupLocation { get; set; }
        public Nullable<int> DisplayTextMaxLength { get; set; }
        public string CustomerDisplayText1 { get; set; }
        public string CustomerDisplayText2 { get; set; }
        public Nullable<int> PrintReceiptBCType { get; set; }
        public Nullable<int> ReceiptBarcodeWidth { get; set; }
        public Nullable<int> ReceiptBarcodeHeight { get; set; }
        public string DefaultSalesType { get; set; }
        public Nullable<int> StaffLoginValidation { get; set; }
        public string HardwareProfile { get; set; }
        public string MenuProfile { get; set; }
        public string InterfaceProfile { get; set; }
        public string FunctionalityProfile { get; set; }
        public string StyleProfile { get; set; }
        public Nullable<byte> PrintNumberOfItems { get; set; }
        public Nullable<byte> PrintSecondReceipt { get; set; }
        public string SalesTypeFilter { get; set; }
        public string DualDisHost { get; set; }
        public string BillNoseri { get; set; }
        public Nullable<long> Counter { get; set; }
        public string Pkey { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
