//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosWebGroup
    {
        public int Id { get; set; }
        public string GroupCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> Level { get; set; }
        public string ParentCode { get; set; }
        public string RefPosGroup { get; set; }
        public Nullable<int> Seq { get; set; }
        public Nullable<long> Counter { get; set; }
        public string Pkey { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<System.DateTime> LastDateModified { get; set; }
        public Nullable<bool> IsPrintLabel { get; set; }
        public Nullable<bool> IsPrintSubBill { get; set; }
    }
}
