//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetailSetup
    {
        public string Key { get; set; }
        public string LocalStoreNo { get; set; }
        public byte LSRetailInUse { get; set; }
        public string EANLicenseNo { get; set; }
        public string DefVATBusPostGrPrice { get; set; }
        public byte DefPriceIncludesVAT { get; set; }
        public string SourceCode { get; set; }
        public string StoreNoNos { get; set; }
        public int ItemSalesStatisticsOn { get; set; }
        public byte POSTerminalStatistics { get; set; }
        public byte StaffStatistics { get; set; }
        public byte PaymentStatistics { get; set; }
        public System.DateTime LastDateModified { get; set; }
        public int DaysBeforeTransArchive { get; set; }
        public byte CommissionActive { get; set; }
        public byte CalculateInStatemPosting { get; set; }
        public byte CalculateInSalesPosting { get; set; }
        public byte ExcludeReturns { get; set; }
        public int BalAccType { get; set; }
        public string BalAccNo { get; set; }
        public byte OriginalSalespersinReturns { get; set; }
        public byte Dimension1Mandatory { get; set; }
        public byte OnlyTwoDimensions { get; set; }
        public int xNumberofRetries { get; set; }
        public string DefaultPriceGroup { get; set; }
        public byte PostTotalDisc { get; set; }
        public byte PostInfocodeDisc { get; set; }
        public byte PostLineDisc { get; set; }
        public byte PostPeriodicDisc { get; set; }
        public byte PostCustDisc { get; set; }
        public byte PostCouponDisc { get; set; }
        public byte PostLineDiscOffer { get; set; }
        public byte PostTotalDiscOffer { get; set; }
        public byte PostTenderTypeDisc { get; set; }
        public int ItemPostingDate { get; set; }
        public int DefaultCustomerPosting { get; set; }
        public byte UpdateCostAmount { get; set; }
        public byte ItemLabelsForNegStock { get; set; }
        public byte ItemLabelsOnPriceChange { get; set; }
        public byte PostAlwaysReserveItems { get; set; }
        public byte DeletePrintedLabels { get; set; }
        public int POItemLookupMethod { get; set; }
        public decimal Difference { get; set; }
        public int AutocreateBarcodes { get; set; }
        public string CreateItemsNoSeries { get; set; }
        public string DefaultItemHierarchy { get; set; }
        public string DistributionLocation { get; set; }
        public string DefStoreHierarchy { get; set; }
        public byte AllowRename { get; set; }
        public Nullable<long> Counter { get; set; }
        public string Pkey { get; set; }
    }
}
