//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewardHeader
    {
        public int ID { get; set; }
        public string RewardNo { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string OfferNo { get; set; }
        public string Link { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<bool> IsReward { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> Counter { get; set; }
        public string Pkey { get; set; }
        public string SubDesc { get; set; }
    }
}
