//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesPriceRate
    {
        public int ID { get; set; }
        public string ItemNo { get; set; }
        public string StoreNo { get; set; }
        public System.DateTime ValidDate { get; set; }
        public string UnitOfMeasureCode { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<long> Counter { get; set; }
        public string Pkey { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
