//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderType
    {
        public long ID { get; set; }
        public string Code { get; set; }
        public string TenderType { get; set; }
        public string Description { get; set; }
        public Nullable<double> Percent { get; set; }
        public string ImageName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Order { get; set; }
        public string HotKey { get; set; }
        public Nullable<int> Counter { get; set; }
        public string Pkey { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string PaymentTenderType { get; set; }
        public Nullable<bool> AllowedReturnedOrder { get; set; }
        public Nullable<bool> IsBlockedLoyalty { get; set; }
        public Nullable<bool> AllowedCardService { get; set; }
        public Nullable<bool> IsBlockedRedeem { get; set; }
        public string PaymentGroup { get; set; }
        public Nullable<bool> AllowedManualInputCardNo { get; set; }
    }
}
