//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesPrice
    {
        public string ItemNo { get; set; }
        public string SalesCode { get; set; }
        public System.DateTime StartingDate { get; set; }
        public string CurrencyCode { get; set; }
        public string UnitOfMeasureCode { get; set; }
        public double UnitPrice { get; set; }
        public byte PriceIncludesVAT { get; set; }
        public byte AllowInvoiceDisc { get; set; }
        public string SalesType { get; set; }
        public Nullable<double> MinimumQuantity { get; set; }
        public System.DateTime EndingDate { get; set; }
        public string VariantCode { get; set; }
        public byte AllowLineDisc { get; set; }
        public Nullable<long> Counter { get; set; }
        public string Pkey { get; set; }
        public int Id { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> LastTimeUpdate { get; set; }
    }
}
