//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupPromotionBUY
    {
        public int ID { get; set; }
        public string Key { get; set; }
        public string FileNameRead { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string Remark { get; set; }
        public string LINEINDICATOR { get; set; }
        public string BUYTYPE { get; set; }
        public string MATGROUP { get; set; }
        public string BBYNR { get; set; }
        public string MAT_NR { get; set; }
        public string MAT_QUAN { get; set; }
        public string MEINH { get; set; }
        public string ScaleType { get; set; }
        public string DiscountType { get; set; }
        public string DiscountValue { get; set; }
    }
}
