//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupSiteCustomerMaster
    {
        public int PID { get; set; }
        public string Key { get; set; }
        public string FileNameRead { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string Remark { get; set; }
        public string SiteNo { get; set; }
        public string OldNo { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string PhoneNo { get; set; }
        public string Mobile { get; set; }
        public string ProvinceId { get; set; }
        public string DistrictId { get; set; }
        public string WardId { get; set; }
        public string StreetId { get; set; }
        public string SupplyRegion { get; set; }
        public string HouseN0 { get; set; }
        public string Address { get; set; }
        public string ContactName { get; set; }
        public string Region { get; set; }
        public string Channel { get; set; }
        public string SalesDistrict { get; set; }
        public string SerchTerm2 { get; set; }
        public string PartnerFunction { get; set; }
        public string CustomerNumber { get; set; }
    }
}
