//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupPromotionHEADER
    {
        public int ID { get; set; }
        public string Key { get; set; }
        public string FileNameRead { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string Remark { get; set; }
        public string HongFileName { get; set; }
        public string LINEINDICATOR { get; set; }
        public string SalesType { get; set; }
        public string BBYNR { get; set; }
        public string BBYTEXT { get; set; }
        public string BBYTYPE { get; set; }
        public string VALIDFROM { get; set; }
        public string VALIDTO { get; set; }
        public string TIMEFROM { get; set; }
        public string TIMETO { get; set; }
        public string MON { get; set; }
        public string TUE { get; set; }
        public string WED { get; set; }
        public string THUR { get; set; }
        public string FRI { get; set; }
        public string SAT { get; set; }
        public string SUN { get; set; }
        public string NUMOFDAYS { get; set; }
        public string BUYLINKCAT { get; set; }
        public string GETLINKCAT { get; set; }
        public string PROMOTION { get; set; }
        public string PROMOTIONTEXT { get; set; }
        public string LIMIT { get; set; }
        public string TOTALMINVALUE { get; set; }
        public string MINVALUE { get; set; }
        public string TOTALDISCOUNT { get; set; }
        public string TOTALDISCOUNTTYPE { get; set; }
        public string TOTALDISCOUNTVALUE { get; set; }
        public string BANKCODE { get; set; }
        public string CARDTYPE { get; set; }
        public string FULLPRICE { get; set; }
        public string STATUS { get; set; }
        public string SITEGROUPCODE { get; set; }
        public string VINID { get; set; }
        public string ZPRIOR { get; set; }
        public string ZVCDATE_ST { get; set; }
        public string ZVCDATE_EN { get; set; }
        public string ZVCDATE_VA { get; set; }
        public string LIMITNR { get; set; }
        public Nullable<bool> IsVoucher { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public string MemberCode { get; set; }
        public Nullable<double> DiscountAmountMax { get; set; }
        public Nullable<bool> IsFULLPRICE { get; set; }
        // TODO: Chưa có cột trong DB - cần chạy ALTER TABLE SetupPromotionHEADER ADD AllowUseAfterDay NVARCHAR(200) NULL, AllowUseAfterTime NVARCHAR(200) NULL
        //public string AllowUseAfterDay { get; set; }
        //public string AllowUseAfterTime { get; set; }
    }
}
