//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupPromotionGET
    {
        public int ID { get; set; }
        public string Key { get; set; }
        public string FileNameRead { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string Remark { get; set; }
        public string LINEINDICATOR { get; set; }
        public string BBYNR { get; set; }
        public string GETTYPE { get; set; }
        public string MATGROUP { get; set; }
        public string MATERIALCODE { get; set; }
        public string DISTYPE { get; set; }
        public string QTY { get; set; }
        public string SCALETYPE { get; set; }
        public string BBYVAL { get; set; }
        public string BBYPER { get; set; }
        public string PRICEUNIT { get; set; }
        public string MEINH { get; set; }
    }
}
