//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupItemLineItem
    {
        public int ID { get; set; }
        public string Key { get; set; }
        public string FileNameRead { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string Remark { get; set; }
        public string HongFileName { get; set; }
        public string MaterialNo { get; set; }
        public string OldNo { get; set; }
        public string ShortDescr { get; set; }
        public string FullDescr { get; set; }
        public string BaseUOM { get; set; }
        public string BrandNo { get; set; }
        public string Model { get; set; }
        public string Blocked { get; set; }
        public string SAL_STATUS { get; set; }
        public string PVALIDFROM { get; set; }
        public string SVALIDFROM { get; set; }
        public string VATGroup { get; set; }
        public string SalesUOM { get; set; }
        public string Level5Code { get; set; }
        public string SpecialAttributes { get; set; }
        public string NoStockPosting { get; set; }
        public string SerialNumCheck { get; set; }
        public string BlockVINID { get; set; }
        public string ArticleType { get; set; }
        public string Prireq { get; set; }
        public string PACKEDATE { get; set; }
        public string SELLBYDATE { get; set; }
        public string INGREDIENT { get; set; }
        public string BESTBFDATE { get; set; }
        public string ParentCode { get; set; }
        public string Size { get; set; }
    }
}
