//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupSalePriceLineItem
    {
        public int ID { get; set; }
        public string Key { get; set; }
        public string FileNameRead { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string Remark { get; set; }
        public string HongFileName { get; set; }
        public string SaleType { get; set; }
        public string ItemNo { get; set; }
        public string NavisionMatNo { get; set; }
        public string Channel { get; set; }
        public string Region { get; set; }
        public string Site { get; set; }
        public string Barcode { get; set; }
        public string SerialNumber { get; set; }
        public string StartingDate { get; set; }
        public string EndingDate { get; set; }
        public string DeleteIndicator { get; set; }
        public string CurrencyCode { get; set; }
        public string UOMCode { get; set; }
        public string PriceIncludesVAT { get; set; }
        public string UnitPriceVAT { get; set; }
        public string Pkey { get; set; }
    }
}
