//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupPromotionSITE
    {
        public int ID { get; set; }
        public string Key { get; set; }
        public string FileNameRead { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string Remark { get; set; }
        public string BBYNR { get; set; }
        public string SITEGROUPCODE { get; set; }
        public string SITECODE { get; set; }
    }
}
