//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialComboLine
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string ItemNo { get; set; }
        public string ItemName { get; set; }
        public string UOM { get; set; }
        public string GroupCode { get; set; }
        public string GroupName { get; set; }
        public Nullable<bool> IsRequired { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<bool> IsSendSAP { get; set; }
        public Nullable<double> MinimumQuantity { get; set; }
        public Nullable<double> MaximumQuantity { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<bool> IsDynamicPrice { get; set; }
        public string Pkey { get; set; }
        public Nullable<long> Counter { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
