//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialComboHeader
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string SalesType { get; set; }
        public string Name { get; set; }
        public Nullable<double> ComboQuantity { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<bool> IsMember { get; set; }
        public string MemberCode { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public string Pkey { get; set; }
        public Nullable<long> Counter { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
