//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class SQLServer
    {
        public int ID { get; set; }
        public string IPServer { get; set; }
        public string NameSvr { get; set; }
        public string UserID { get; set; }
        public string Password { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Code { get; set; }
        public Nullable<bool> IsSetDB { get; set; }
        public string IpServer2 { get; set; }
        public string VIP { get; set; }
        public string IPServerRead { get; set; }
    }
}
