//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class StackTraceLog
    {
        public long ID { get; set; }
        public string UserName { get; set; }
        public string StoreNo { get; set; }
        public string POSTerminal { get; set; }
        public string Description { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string ActionType { get; set; }
        public string JSONModel { get; set; }
        public string MessageError { get; set; }
        public Nullable<System.DateTime> ErrorDateTime { get; set; }
        public string IPServer { get; set; }
        public string URL { get; set; }
        public string Source { get; set; }
        public string RefKey1 { get; set; }
        public string RefKey2 { get; set; }
        public string RefKey3 { get; set; }
        public string RefKey4 { get; set; }
        public string RefKey5 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
