//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public string ID { get; set; }
        public string Password { get; set; }
        public Nullable<byte> ChangePassword { get; set; }
        public string StoreNo { get; set; }
        public Nullable<int> VoidTransaction { get; set; }
        public Nullable<int> ManagerPrivileges { get; set; }
        public Nullable<int> TenderDeclaration { get; set; }
        public Nullable<int> FloatingDeclaration { get; set; }
        public Nullable<int> PriceOverride { get; set; }
        public Nullable<double> MaxDiscountToGive { get; set; }
        public Nullable<int> SuspendTransaction { get; set; }
        public Nullable<double> MaxTotalDiscount { get; set; }
        public Nullable<int> OpenDrawWithoutSale { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> EmploymentType { get; set; }
        public Nullable<double> FraudSortField { get; set; }
        public Nullable<System.DateTime> LastDateModified { get; set; }
        public string NameOnReceipt { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string PostCode { get; set; }
        public string HomePhoneNo { get; set; }
        public string WorkPhoneNo { get; set; }
        public Nullable<double> HourlyRate { get; set; }
        public string PayrollNo { get; set; }
        public Nullable<byte> Blocked { get; set; }
        public Nullable<System.DateTime> DateToBeBlocked { get; set; }
        public Nullable<byte> LeftHanded { get; set; }
        public string SalesPerson { get; set; }
        public string PermissionGroup { get; set; }
        public Nullable<int> ReturnInTransaction { get; set; }
        public Nullable<int> VoidPrepayment { get; set; }
        public Nullable<int> VoidPrepaymentLine { get; set; }
        public Nullable<int> ChangePrepaymentAmt { get; set; }
        public Nullable<int> AddPrepaymentAmt { get; set; }
        public Nullable<int> VoidLine { get; set; }
        public Nullable<int> AddPayment { get; set; }
        public Nullable<int> SplitBills { get; set; }
        public string Language { get; set; }
        public Nullable<int> CreateCustomers { get; set; }
        public Nullable<int> ViewSalesHistory { get; set; }
        public Nullable<int> UpdateCustomers { get; set; }
        public Nullable<byte> InventoryActive { get; set; }
        public string InventoryMainMenu { get; set; }
        public string POSStyleProfile { get; set; }
        public string POSMenuProfile { get; set; }
        public Nullable<int> DeliverStatus { get; set; }
        public Nullable<long> Counter { get; set; }
        public string Pkey { get; set; }
    }
}
