//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreNoMapping
    {
        public int ID { get; set; }
        public string StoreNoBlue { get; set; }
        public string StoreNoPLH { get; set; }
        public string StoreNoWPH { get; set; }
        public Nullable<int> Counter { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModelType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    }
}
