//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncWriteFileLog
    {
        public int ID { get; set; }
        public string FileName { get; set; }
        public string Type { get; set; }
        public string ErrorMsg { get; set; }
        public Nullable<int> Step { get; set; }
        public string ProcessID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
