//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncAction
    {
        public long ID { get; set; }
        public string TransType { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string StoreNo { get; set; }
        public string TableName { get; set; }
        public string ActionType { get; set; }
        public string Pkey { get; set; }
        public Nullable<long> Counter { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsSend { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
