//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncChangeLog
    {
        public decimal ID { get; set; }
        public string SiteCode { get; set; }
        public string PosTerminal { get; set; }
        public string TableName { get; set; }
        public Nullable<System.DateTime> SyncTime { get; set; }
        public Nullable<long> LastCounter { get; set; }
    }
}
