//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncTableList
    {
        public int ID { get; set; }
        public string TableName { get; set; }
        public Nullable<long> POSLastCounter { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public string Procedure { get; set; }
        public Nullable<bool> IsOnlyChange { get; set; }
        public Nullable<bool> IsAll { get; set; }
        public Nullable<int> OrderByName { get; set; }
        public Nullable<bool> IsByStore { get; set; }
        public Nullable<bool> IsSAP { get; set; }
        public Nullable<bool> IsApplyDel { get; set; }
        public string GroupName { get; set; }
        public string ColumnFilter { get; set; }
        public Nullable<bool> IsFirstDataAll { get; set; }
    }
}
