//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncDateLog
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Folder { get; set; }
        public Nullable<short> Status { get; set; }
        public string ErrorMsg { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string FolderFileZip { get; set; }
        public string FileNameZip { get; set; }
        public string ProcessID { get; set; }
        public Nullable<int> FileQty { get; set; }
    }
}
