//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncJobLogCounter
    {
        public int ID { get; set; }
        public string StoreNo { get; set; }
        public string Posterminal { get; set; }
        public string FileName { get; set; }
        public string TableName { get; set; }
        public string CounterList { get; set; }
        public Nullable<int> MinCounter { get; set; }
        public Nullable<int> MaxCounter { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
