//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncJobLog
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public string Message { get; set; }
        public Nullable<int> TotalRecord { get; set; }
        public string TableName { get; set; }
        public string FileName { get; set; }
        public string ActionTable { get; set; }
        public string SiteNo { get; set; }
        public string PosTerminal { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastCounter { get; set; }
        public string ProcessID { get; set; }
        public Nullable<int> RecordOnFile { get; set; }
        public Nullable<int> MinCounter { get; set; }
        public string CounterList { get; set; }
    }
}
