//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysWebApiRoute
    {
        public string AppCode { get; set; }
        public string Name { get; set; }
        public string Route { get; set; }
        public string Description { get; set; }
        public bool Blocked { get; set; }
        public string Version { get; set; }
        public string Notes { get; set; }
    
        public virtual SysWebApi SysWebApi { get; set; }
    }
}
