//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenderType
    {
        public byte[] timestamp { get; set; }
        public string StoreNo { get; set; }
        public string Code { get; set; }
        public string PrimaryCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> Function { get; set; }
        public string ChangeTenderCode { get; set; }
        public Nullable<int> Rounding { get; set; }
        public Nullable<double> RoundingTo { get; set; }
        public Nullable<double> MinAmountEntered { get; set; }
        public Nullable<double> MaxAmountEntered { get; set; }
        public Nullable<double> MinAmountAllowed { get; set; }
        public Nullable<double> MaxAmountAllowed { get; set; }
        public Nullable<byte> MayBeUsed { get; set; }
        public Nullable<bool> AllowedReturnedOrder { get; set; }
        public Nullable<byte> ManagerKeyControl { get; set; }
        public Nullable<byte> KeyboardEntryAllowed { get; set; }
        public Nullable<byte> OvertenderAllowed { get; set; }
        public Nullable<double> OvertenderMaxAmt { get; set; }
        public Nullable<byte> DrawerOpens { get; set; }
        public Nullable<byte> CardAccountNo { get; set; }
        public Nullable<byte> AskForDate { get; set; }
        public Nullable<byte> ForeignCurrency { get; set; }
        public Nullable<byte> FloatAllowed { get; set; }
        public Nullable<int> BankAccountType { get; set; }
        public string BankAccountNo { get; set; }
        public string BankAccountName { get; set; }
        public Nullable<byte> ReturnVoucher { get; set; }
        public string AccountNo { get; set; }
        public Nullable<long> Counter { get; set; }
        public string Pkey { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> AllowedPaymentPart { get; set; }
        public Nullable<bool> AllowedPromotion { get; set; }
        public string Caption { get; set; }
        public Nullable<int> SeqOnPOS { get; set; }
    }
}
