//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenderTypeConfig
    {
        public int ID { get; set; }
        public string TenderTypeCode { get; set; }
        public string IssueVATTo { get; set; }
        public Nullable<bool> IsFullPayment { get; set; }
        public string Refkey1 { get; set; }
        public string Refkey2 { get; set; }
        public string Refkey3 { get; set; }
        public string Refkey4 { get; set; }
        public string Refkey5 { get; set; }
        public string Refkey6 { get; set; }
        public string Refkey7 { get; set; }
        public string Refkey8 { get; set; }
        public string Refkey9 { get; set; }
        public string Refkey10 { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Pkey { get; set; }
        public Nullable<long> Counter { get; set; }
    }
}
