//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransInputData
    {
        public byte[] timestamp { get; set; }
        public string TransNo { get; set; }
        public int LineNumber { get; set; }
        public string TableName { get; set; }
        public string DataType { get; set; }
        public string DataValue { get; set; }
        public Nullable<long> Counter { get; set; }
    }
}
