//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransInfocodeEntry
    {
        public byte[] timestamp { get; set; }
        public string OrderNo { get; set; }
        public int OrderLineNo { get; set; }
        public int LineNo { get; set; }
        public int TransactionType { get; set; }
        public string Infocode { get; set; }
        public string Infomation { get; set; }
        public int TypeOfInput { get; set; }
        public int TextType { get; set; }
        public string ItemNo { get; set; }
        public string SourceCode { get; set; }
        public Nullable<double> Amount { get; set; }
        public string SubCode { get; set; }
        public int ParentLineNo { get; set; }
        public Nullable<long> Counter { get; set; }
    }
}
