//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransPartnerLine
    {
        public string OrderNo { get; set; }
        public int LineNo { get; set; }
        public Nullable<int> OrderLineNo { get; set; }
        public string PartnerCode { get; set; }
        public string ServiceType { get; set; }
        public string ServiceCode { get; set; }
        public string Serial { get; set; }
        public string Pin { get; set; }
        public Nullable<System.DateTime> Expiry { get; set; }
        public Nullable<double> Value { get; set; }
        public string Note { get; set; }
    }
}
