//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransOptionLine
    {
        public string OrderNo { get; set; }
        public int LineNo { get; set; }
        public Nullable<int> OrderLineNo { get; set; }
        public string SaleTypeCode { get; set; }
        public string Type { get; set; }
        public string ItemNo { get; set; }
        public string UOM { get; set; }
        public string Description { get; set; }
        public string OptionType { get; set; }
        public string OptionName { get; set; }
        public Nullable<double> OptionQuantity { get; set; }
        public string Note { get; set; }
        public string ItemNoRef { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    }
}
