//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransDiscountCouponEntry
    {
        public byte[] timestamp { get; set; }
        public string OrderNo { get; set; }
        public int OrderLineNo { get; set; }
        public int LineNo { get; set; }
        public string OfferType { get; set; }
        public string OfferNo { get; set; }
        public Nullable<double> Quantity { get; set; }
        public int DiscountType { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public string Barcode { get; set; }
        public int ParentLineNo { get; set; }
        public string ItemNo { get; set; }
        public string LineGroup { get; set; }
        public Nullable<long> Counter { get; set; }
        public Nullable<bool> IsCheckAPI { get; set; }
        public Nullable<bool> IsTotalBill { get; set; }
    }
}
