//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransPaymentEntry
    {
        public byte[] timestamp { get; set; }
        public string OrderNo { get; set; }
        public int LineNo { get; set; }
        public string StoreNo { get; set; }
        public string POSTerminalNo { get; set; }
        public int TransactionNo { get; set; }
        public string ReceiptNo { get; set; }
        public string StatementCode { get; set; }
        public string CardNo { get; set; }
        public Nullable<double> ExchangeRate { get; set; }
        public string TenderType { get; set; }
        public string TenderTypeName { get; set; }
        public Nullable<double> AmountTendered { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<double> AmountInCurrency { get; set; }
        public string CardOrAccount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public System.DateTime PaymentTime { get; set; }
        public string ShiftNo { get; set; }
        public System.DateTime ShiftDate { get; set; }
        public string StaffID { get; set; }
        public int CardPaymentType { get; set; }
        public Nullable<double> CardValue { get; set; }
        public string ReferenceNo { get; set; }
        public string PayForOrderNo { get; set; }
        public Nullable<long> Counter { get; set; }
        public string ApprovalCode { get; set; }
        public string BankPOSCode { get; set; }
        public string BankCardType { get; set; }
        public Nullable<bool> IsOnline { get; set; }
        public Nullable<bool> IsCommission { get; set; }
        public Nullable<double> CommissionPercent { get; set; }
        public string Partner { get; set; }
        public Nullable<double> GiftRedeemPoint { get; set; }
        public Nullable<int> OrderLineNo { get; set; }
        public string CustomerPaymentCode { get; set; }
        public string PaymentType { get; set; }
        public string TransactionId { get; set; }
    }
}
