//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransLine
    {
        public byte[] timestamp { get; set; }
        public int LineNo { get; set; }
        public string DocumentNo { get; set; }
        public Nullable<int> LineType { get; set; }
        public string LocationCode { get; set; }
        public string ItemNo { get; set; }
        public string Description { get; set; }
        public string UnitOfMeasure { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> OfferUnitPrice { get; set; }
        public Nullable<double> AmountBeforeDiscount { get; set; }
        public Nullable<double> DiscountPercent { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<double> VATPercent { get; set; }
        public Nullable<double> VATAmount { get; set; }
        public Nullable<double> LineAmountIncVAT { get; set; }
        public string OfferNo { get; set; }
        public Nullable<int> DiscountType { get; set; }
        public Nullable<double> TriggerQuantity { get; set; }
        public string StaffID { get; set; }
        public Nullable<double> PrepaymentAmount { get; set; }
        public string VATCode { get; set; }
        public Nullable<int> DeliveringMethod { get; set; }
        public string Barcode { get; set; }
        public Nullable<double> OrderDiscountPercent { get; set; }
        public Nullable<double> OrderDiscountAmount { get; set; }
        public string DivisionCode { get; set; }
        public string CategoryCode { get; set; }
        public string ProductGroupCode { get; set; }
        public Nullable<byte> BlockedMemberPoint { get; set; }
        public string SerialNo { get; set; }
        public string OrigTransStore { get; set; }
        public string OrigTransPos { get; set; }
        public Nullable<int> OrigTransNo { get; set; }
        public Nullable<int> OrigTransLineNo { get; set; }
        public string OrigOrderNo { get; set; }
        public Nullable<int> OrigLineNumber { get; set; }
        public Nullable<byte> BlockedPromotion { get; set; }
        public string Infocodes { get; set; }
        public Nullable<double> MemberPointsEarn { get; set; }
        public Nullable<double> ReturnedQuantity { get; set; }
        public Nullable<double> DeliveryQuantity { get; set; }
        public Nullable<int> DeliveryStatus { get; set; }
        public Nullable<double> MemberPointsRedeem { get; set; }
        public string VariantNo { get; set; }
        public string LotNo { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<double> AmountCalPoint { get; set; }
        public string WaitingListNo { get; set; }
        public string ArticleType { get; set; }
        public Nullable<System.DateTime> ScanTime { get; set; }
        public string DiscountCode { get; set; }
        public string PromotionGroup { get; set; }
        public Nullable<long> Counter { get; set; }
        public Nullable<int> LineNoEffect { get; set; }
        public Nullable<double> DiscountQuantity { get; set; }
        public Nullable<double> DiscountUnit { get; set; }
        public Nullable<int> SnGLineID { get; set; }
        public Nullable<double> QtyDiscount { get; set; }
        public Nullable<double> QtyDiscountReturned { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsTopping { get; set; }
        public string Group { get; set; }
        public string ParentCode { get; set; }
        public string GuiID { get; set; }
        public Nullable<bool> IsCombo { get; set; }
        public string ComboName { get; set; }
        public Nullable<bool> IsGift { get; set; }
        public string GiftGroup { get; set; }
        public Nullable<double> ComboQuantity { get; set; }
        public Nullable<bool> IsGiftRedeem { get; set; }
        public Nullable<double> GiftRedeemPoint { get; set; }
        public Nullable<bool> IsVAT { get; set; }
        public Nullable<bool> IsFee { get; set; }
        public Nullable<bool> IsChangeCardFee { get; set; }
        public string ChangeCardId { get; set; }
        public string ChangeCardCodeValue { get; set; }
        public string ChangeCardType { get; set; }
        public Nullable<bool> ChangeCardOTP { get; set; }
        public Nullable<bool> IsBirthdayGift { get; set; }
        public Nullable<bool> IsAllowReturn { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ComboType { get; set; }
        public Nullable<bool> IsDynamicPrice { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
        public string Ref3 { get; set; }
        public string Ref4 { get; set; }
        public string Ref5 { get; set; }
        public string Ref6 { get; set; }
        public string Ref7 { get; set; }
        public string Ref8 { get; set; }
        public string Ref9 { get; set; }
        public string Ref10 { get; set; }
    }
}
