//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public byte[] timestamp { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public int State { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string WindowsSecurityID { get; set; }
        public byte ChangePassword { get; set; }
        public int LicenseType { get; set; }
        public string AuthenticationEmail { get; set; }
        public string StoreNo { get; set; }
        public Nullable<long> Counter { get; set; }
        public string Pkey { get; set; }
    }
}
