//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class VatNumber
    {
        public int ID { get; set; }
        public string CompTaxCode { get; set; }
        public string NoseriCode { get; set; }
        public string InvoicePattern { get; set; }
        public string SerialNo { get; set; }
        public string StartNumber { get; set; }
        public string EndNumber { get; set; }
        public string LastUsed { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
