//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeightScale_Processing
    {
        public int ID { get; set; }
        public string StoreNo { get; set; }
        public Nullable<bool> IsChange { get; set; }
        public Nullable<bool> IsFinish { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> FinishedDate { get; set; }
        public Nullable<bool> IsFormatMultimex { get; set; }
        public Nullable<bool> IsFormatStandard { get; set; }
    }
}
