//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeightScale_PLU_LIST
    {
        public string PLU_NO { get; set; }
        public string PLU_TYPE { get; set; }
        public string ITEMCODE { get; set; }
        public string ITEMNAME { get; set; }
        public string LABEL_NO { get; set; }
        public Nullable<int> PACKEDATE { get; set; }
        public Nullable<int> SELLBYDATE { get; set; }
        public string INGREDIENT { get; set; }
        public Nullable<int> BESTBFDATE { get; set; }
        public string ET1 { get; set; }
        public string ET2 { get; set; }
        public string ITEM_NO { get; set; }
        public string UOM { get; set; }
        public string BARCODE { get; set; }
        public string PKEY { get; set; }
        public Nullable<long> Counter { get; set; }
        public Nullable<bool> Enable { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
    }
}
