//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class WinCodeCustomer
    {
        public System.Guid ID { get; set; }
        public string WinCode { get; set; }
        public string MemberCard { get; set; }
        public string Csn { get; set; }
        public Nullable<int> QuantityRecieptedSum { get; set; }
        public Nullable<int> QuantityReciepted { get; set; }
        public string OrderNo { get; set; }
        public string StoreNo { get; set; }
        public string PosNo { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    }
}
