//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace VCM.POSBLUE.API.SAPOdoo {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_VC_OUTBinding", Namespace="urn:phuclong:s4:voucher:to:odoo:ws")]
    public partial class SI_VC_OUTService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_VC_GEN_OUTOperationCompleted;
        
        private System.Threading.SendOrPostCallback SI_VC_UPDATE_OUTOperationCompleted;
        
        private System.Threading.SendOrPostCallback SI_VC_CHECK_OUTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_VC_OUTService() {
            this.Url = global::VCM.POSBLUE.API.Properties.Settings.Default.VCM_POSBLUE_API_SAPOdoo_SI_VC_OUTService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_VC_GEN_OUTCompletedEventHandler SI_VC_GEN_OUTCompleted;
        
        /// <remarks/>
        public event SI_VC_UPDATE_OUTCompletedEventHandler SI_VC_UPDATE_OUTCompleted;
        
        /// <remarks/>
        public event SI_VC_CHECK_OUTCompletedEventHandler SI_VC_CHECK_OUTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("MT_ODOO_VC_GEN_RESPONSE", Namespace="urn:phuclong:s4:voucher:to:odoo:ws")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("RESPONSE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_ODOO_VC_GEN_RESPONSERESPONSE[] SI_VC_GEN_OUT([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:phuclong:s4:voucher:to:odoo:ws")] DT_ODOO_VC_GEN_REQUEST MT_ODOO_VC_GEN_REQUEST) {
            object[] results = this.Invoke("SI_VC_GEN_OUT", new object[] {
                        MT_ODOO_VC_GEN_REQUEST});
            return ((DT_ODOO_VC_GEN_RESPONSERESPONSE[])(results[0]));
        }
        
        /// <remarks/>
        public void SI_VC_GEN_OUTAsync(DT_ODOO_VC_GEN_REQUEST MT_ODOO_VC_GEN_REQUEST) {
            this.SI_VC_GEN_OUTAsync(MT_ODOO_VC_GEN_REQUEST, null);
        }
        
        /// <remarks/>
        public void SI_VC_GEN_OUTAsync(DT_ODOO_VC_GEN_REQUEST MT_ODOO_VC_GEN_REQUEST, object userState) {
            if ((this.SI_VC_GEN_OUTOperationCompleted == null)) {
                this.SI_VC_GEN_OUTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_VC_GEN_OUTOperationCompleted);
            }
            this.InvokeAsync("SI_VC_GEN_OUT", new object[] {
                        MT_ODOO_VC_GEN_REQUEST}, this.SI_VC_GEN_OUTOperationCompleted, userState);
        }
        
        private void OnSI_VC_GEN_OUTOperationCompleted(object arg) {
            if ((this.SI_VC_GEN_OUTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_VC_GEN_OUTCompleted(this, new SI_VC_GEN_OUTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("MT_ODOO_VC_UPDATE_RESPONSE", Namespace="urn:phuclong:s4:voucher:to:odoo:ws")]
        public DT_ODOO_VC_UPDATE_RESPONSE SI_VC_UPDATE_OUT([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:phuclong:s4:voucher:to:odoo:ws")] DT_ODOO_VC_UPDATE_REQUEST MT_ODOO_VC_UPDATE_REQUEST) {
            object[] results = this.Invoke("SI_VC_UPDATE_OUT", new object[] {
                        MT_ODOO_VC_UPDATE_REQUEST});
            return ((DT_ODOO_VC_UPDATE_RESPONSE)(results[0]));
        }
        
        /// <remarks/>
        public void SI_VC_UPDATE_OUTAsync(DT_ODOO_VC_UPDATE_REQUEST MT_ODOO_VC_UPDATE_REQUEST) {
            this.SI_VC_UPDATE_OUTAsync(MT_ODOO_VC_UPDATE_REQUEST, null);
        }
        
        /// <remarks/>
        public void SI_VC_UPDATE_OUTAsync(DT_ODOO_VC_UPDATE_REQUEST MT_ODOO_VC_UPDATE_REQUEST, object userState) {
            if ((this.SI_VC_UPDATE_OUTOperationCompleted == null)) {
                this.SI_VC_UPDATE_OUTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_VC_UPDATE_OUTOperationCompleted);
            }
            this.InvokeAsync("SI_VC_UPDATE_OUT", new object[] {
                        MT_ODOO_VC_UPDATE_REQUEST}, this.SI_VC_UPDATE_OUTOperationCompleted, userState);
        }
        
        private void OnSI_VC_UPDATE_OUTOperationCompleted(object arg) {
            if ((this.SI_VC_UPDATE_OUTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_VC_UPDATE_OUTCompleted(this, new SI_VC_UPDATE_OUTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("MT_ODOO_VC_CHECK_RESPONSE", Namespace="urn:phuclong:s4:voucher:to:odoo:ws")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("RESPONSE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_ODOO_VC_CHECK_RESPONSERESPONSE[] SI_VC_CHECK_OUT([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:phuclong:s4:voucher:to:odoo:ws")] DT_ODOO_VC_CHECK_REQUEST MT_ODOO_VC_CHECK_REQUEST) {
            object[] results = this.Invoke("SI_VC_CHECK_OUT", new object[] {
                        MT_ODOO_VC_CHECK_REQUEST});
            return ((DT_ODOO_VC_CHECK_RESPONSERESPONSE[])(results[0]));
        }
        
        /// <remarks/>
        public void SI_VC_CHECK_OUTAsync(DT_ODOO_VC_CHECK_REQUEST MT_ODOO_VC_CHECK_REQUEST) {
            this.SI_VC_CHECK_OUTAsync(MT_ODOO_VC_CHECK_REQUEST, null);
        }
        
        /// <remarks/>
        public void SI_VC_CHECK_OUTAsync(DT_ODOO_VC_CHECK_REQUEST MT_ODOO_VC_CHECK_REQUEST, object userState) {
            if ((this.SI_VC_CHECK_OUTOperationCompleted == null)) {
                this.SI_VC_CHECK_OUTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_VC_CHECK_OUTOperationCompleted);
            }
            this.InvokeAsync("SI_VC_CHECK_OUT", new object[] {
                        MT_ODOO_VC_CHECK_REQUEST}, this.SI_VC_CHECK_OUTOperationCompleted, userState);
        }
        
        private void OnSI_VC_CHECK_OUTOperationCompleted(object arg) {
            if ((this.SI_VC_CHECK_OUTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_VC_CHECK_OUTCompleted(this, new SI_VC_CHECK_OUTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:phuclong:s4:voucher:to:odoo:ws")]
    public partial class DT_ODOO_VC_GEN_REQUEST {
        
        private DT_ODOO_VC_GEN_REQUESTREQUEST rEQUESTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_ODOO_VC_GEN_REQUESTREQUEST REQUEST {
            get {
                return this.rEQUESTField;
            }
            set {
                this.rEQUESTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:phuclong:s4:voucher:to:odoo:ws")]
    public partial class DT_ODOO_VC_GEN_REQUESTREQUEST {
        
        private string mATERIALNUMBERField;
        
        private string sALESPLANTField;
        
        private string sALESPRICEField;
        
        private string dISCOUNTField;
        
        private string sALESDATEField;
        
        private string sALESTRANSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATERIALNUMBER {
            get {
                return this.mATERIALNUMBERField;
            }
            set {
                this.mATERIALNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SALESPLANT {
            get {
                return this.sALESPLANTField;
            }
            set {
                this.sALESPLANTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SALESPRICE {
            get {
                return this.sALESPRICEField;
            }
            set {
                this.sALESPRICEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DISCOUNT {
            get {
                return this.dISCOUNTField;
            }
            set {
                this.dISCOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SALESDATE {
            get {
                return this.sALESDATEField;
            }
            set {
                this.sALESDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SALESTRANS {
            get {
                return this.sALESTRANSField;
            }
            set {
                this.sALESTRANSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:phuclong:s4:voucher:to:odoo:ws")]
    public partial class DT_ODOO_VC_CHECK_REQUEST {
        
        private DT_ODOO_VC_CHECK_REQUESTREQUEST rEQUESTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_ODOO_VC_CHECK_REQUESTREQUEST REQUEST {
            get {
                return this.rEQUESTField;
            }
            set {
                this.rEQUESTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:phuclong:s4:voucher:to:odoo:ws")]
    public partial class DT_ODOO_VC_CHECK_REQUESTREQUEST {
        
        private string sERIALNUMBERField;
        
        private string iSVOUCHERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SERIALNUMBER {
            get {
                return this.sERIALNUMBERField;
            }
            set {
                this.sERIALNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ISVOUCHER {
            get {
                return this.iSVOUCHERField;
            }
            set {
                this.iSVOUCHERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:phuclong:s4:voucher:to:odoo:ws")]
    public partial class DT_ODOO_VC_UPDATE_RESPONSE {
        
        private DT_ODOO_VC_UPDATE_RESPONSERESPONSE rESPONSEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_ODOO_VC_UPDATE_RESPONSERESPONSE RESPONSE {
            get {
                return this.rESPONSEField;
            }
            set {
                this.rESPONSEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:phuclong:s4:voucher:to:odoo:ws")]
    public partial class DT_ODOO_VC_UPDATE_RESPONSERESPONSE {
        
        private string rEDEEMPLANTField;
        
        private string sERIALNUMBERField;
        
        private string sTATUSCODEField;
        
        private string mATERIALNUMBERField;
        
        private string rEMAINAMOUNTField;
        
        private string sTATUSMESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REDEEMPLANT {
            get {
                return this.rEDEEMPLANTField;
            }
            set {
                this.rEDEEMPLANTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SERIALNUMBER {
            get {
                return this.sERIALNUMBERField;
            }
            set {
                this.sERIALNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STATUSCODE {
            get {
                return this.sTATUSCODEField;
            }
            set {
                this.sTATUSCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATERIALNUMBER {
            get {
                return this.mATERIALNUMBERField;
            }
            set {
                this.mATERIALNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REMAINAMOUNT {
            get {
                return this.rEMAINAMOUNTField;
            }
            set {
                this.rEMAINAMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STATUSMESSAGE {
            get {
                return this.sTATUSMESSAGEField;
            }
            set {
                this.sTATUSMESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:phuclong:s4:voucher:to:odoo:ws")]
    public partial class DT_ODOO_VC_UPDATE_REQUEST {
        
        private DT_ODOO_VC_UPDATE_REQUESTREQUEST rEQUESTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_ODOO_VC_UPDATE_REQUESTREQUEST REQUEST {
            get {
                return this.rEQUESTField;
            }
            set {
                this.rEQUESTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:phuclong:s4:voucher:to:odoo:ws")]
    public partial class DT_ODOO_VC_UPDATE_REQUESTREQUEST {
        
        private string sERIALNUMBERField;
        
        private string iSVOUCHERField;
        
        private string sTATUSCODEField;
        
        private string sALESPLANTField;
        
        private string sALESPRICEField;
        
        private string dISCOUNTField;
        
        private string sALESDATEField;
        
        private string sALESTRANSField;
        
        private string rEDEEMAMOUNTField;
        
        private string rEDEEMPLANTField;
        
        private string rEDEEMDATEField;
        
        private string rEDEEMTRANSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SERIALNUMBER {
            get {
                return this.sERIALNUMBERField;
            }
            set {
                this.sERIALNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ISVOUCHER {
            get {
                return this.iSVOUCHERField;
            }
            set {
                this.iSVOUCHERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STATUSCODE {
            get {
                return this.sTATUSCODEField;
            }
            set {
                this.sTATUSCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SALESPLANT {
            get {
                return this.sALESPLANTField;
            }
            set {
                this.sALESPLANTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SALESPRICE {
            get {
                return this.sALESPRICEField;
            }
            set {
                this.sALESPRICEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DISCOUNT {
            get {
                return this.dISCOUNTField;
            }
            set {
                this.dISCOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SALESDATE {
            get {
                return this.sALESDATEField;
            }
            set {
                this.sALESDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SALESTRANS {
            get {
                return this.sALESTRANSField;
            }
            set {
                this.sALESTRANSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REDEEMAMOUNT {
            get {
                return this.rEDEEMAMOUNTField;
            }
            set {
                this.rEDEEMAMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REDEEMPLANT {
            get {
                return this.rEDEEMPLANTField;
            }
            set {
                this.rEDEEMPLANTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REDEEMDATE {
            get {
                return this.rEDEEMDATEField;
            }
            set {
                this.rEDEEMDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REDEEMTRANS {
            get {
                return this.rEDEEMTRANSField;
            }
            set {
                this.rEDEEMTRANSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:phuclong:s4:voucher:to:odoo:ws")]
    public partial class DT_ODOO_VC_GEN_RESPONSERESPONSE {
        
        private string sALESPLANTField;
        
        private string sERIALVOUCHERField;
        
        private string fROMDATEField;
        
        private string tODATEField;
        
        private string vOUCHERVALUEField;
        
        private string sTATUSCODEField;
        
        private string mATERIALNUMBERField;
        
        private string sTATUSMESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SALESPLANT {
            get {
                return this.sALESPLANTField;
            }
            set {
                this.sALESPLANTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SERIALVOUCHER {
            get {
                return this.sERIALVOUCHERField;
            }
            set {
                this.sERIALVOUCHERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FROMDATE {
            get {
                return this.fROMDATEField;
            }
            set {
                this.fROMDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TODATE {
            get {
                return this.tODATEField;
            }
            set {
                this.tODATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VOUCHERVALUE {
            get {
                return this.vOUCHERVALUEField;
            }
            set {
                this.vOUCHERVALUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STATUSCODE {
            get {
                return this.sTATUSCODEField;
            }
            set {
                this.sTATUSCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATERIALNUMBER {
            get {
                return this.mATERIALNUMBERField;
            }
            set {
                this.mATERIALNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STATUSMESSAGE {
            get {
                return this.sTATUSMESSAGEField;
            }
            set {
                this.sTATUSMESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:phuclong:s4:voucher:to:odoo:ws")]
    public partial class DT_ODOO_VC_CHECK_RESPONSERESPONSE {
        
        private string sERIALNUMBERField;
        
        private string fROMDATEField;
        
        private string tODATEField;
        
        private string vALUEField;
        
        private string rEMAINAMOUNTField;
        
        private string sTATUSCODEField;
        
        private string mATERIALNUMBERField;
        
        private string sALESDATEField;
        
        private string sALESTRANSField;
        
        private string rEDEEMTRANSField;
        
        private string rEDEEMDATEField;
        
        private string rEDEEMPLANTField;
        
        private string iSEMPLOYEEField;
        
        private string sTATUSMESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SERIALNUMBER {
            get {
                return this.sERIALNUMBERField;
            }
            set {
                this.sERIALNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FROMDATE {
            get {
                return this.fROMDATEField;
            }
            set {
                this.fROMDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TODATE {
            get {
                return this.tODATEField;
            }
            set {
                this.tODATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VALUE {
            get {
                return this.vALUEField;
            }
            set {
                this.vALUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REMAINAMOUNT {
            get {
                return this.rEMAINAMOUNTField;
            }
            set {
                this.rEMAINAMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STATUSCODE {
            get {
                return this.sTATUSCODEField;
            }
            set {
                this.sTATUSCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATERIALNUMBER {
            get {
                return this.mATERIALNUMBERField;
            }
            set {
                this.mATERIALNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SALESDATE {
            get {
                return this.sALESDATEField;
            }
            set {
                this.sALESDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SALESTRANS {
            get {
                return this.sALESTRANSField;
            }
            set {
                this.sALESTRANSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REDEEMTRANS {
            get {
                return this.rEDEEMTRANSField;
            }
            set {
                this.rEDEEMTRANSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REDEEMDATE {
            get {
                return this.rEDEEMDATEField;
            }
            set {
                this.rEDEEMDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REDEEMPLANT {
            get {
                return this.rEDEEMPLANTField;
            }
            set {
                this.rEDEEMPLANTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ISEMPLOYEE {
            get {
                return this.iSEMPLOYEEField;
            }
            set {
                this.iSEMPLOYEEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STATUSMESSAGE {
            get {
                return this.sTATUSMESSAGEField;
            }
            set {
                this.sTATUSMESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SI_VC_GEN_OUTCompletedEventHandler(object sender, SI_VC_GEN_OUTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_VC_GEN_OUTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SI_VC_GEN_OUTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_ODOO_VC_GEN_RESPONSERESPONSE[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_ODOO_VC_GEN_RESPONSERESPONSE[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SI_VC_UPDATE_OUTCompletedEventHandler(object sender, SI_VC_UPDATE_OUTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_VC_UPDATE_OUTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SI_VC_UPDATE_OUTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_ODOO_VC_UPDATE_RESPONSE Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_ODOO_VC_UPDATE_RESPONSE)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SI_VC_CHECK_OUTCompletedEventHandler(object sender, SI_VC_CHECK_OUTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_VC_CHECK_OUTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SI_VC_CHECK_OUTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_ODOO_VC_CHECK_RESPONSERESPONSE[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_ODOO_VC_CHECK_RESPONSERESPONSE[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591