//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.PartnerPLH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shopee_update_order_backup
    {
        public long Id { get; set; }
        public string order_code { get; set; }
        public int update_type { get; set; }
        public Nullable<int> restaurant_id { get; set; }
        public string pick_time { get; set; }
        public int status { get; set; }
        public string merchant_note { get; set; }
        public string note_for_shipper { get; set; }
        public string partner_restaurant_id { get; set; }
        public string serial { get; set; }
        public System.DateTime crt_date { get; set; }
        public System.DateTime chg_date { get; set; }
        public string update_flg { get; set; }
        public string message { get; set; }
        public string crt_user { get; set; }
        public string raw_data { get; set; }
    }
}
