//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.POSBLUE.Data.DataBaseContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CentralMDContainer : DbContext
    {
        public CentralMDContainer()
            : base("name=CentralMDContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CpnVchBOMCodeIssue> CpnVchBOMCodeIssues { get; set; }
        public virtual DbSet<CpnVchBOMHeader> CpnVchBOMHeaders { get; set; }
        public virtual DbSet<CpnVchBOMLine> CpnVchBOMLines { get; set; }
        public virtual DbSet<CpnVchCodeSend> CpnVchCodeSends { get; set; }
        public virtual DbSet<CXOfflinePercent> CXOfflinePercents { get; set; }
        public virtual DbSet<POSDataSetup> POSDataSetups { get; set; }
        public virtual DbSet<POSTerminal> POSTerminals { get; set; }
        public virtual DbSet<POSVersion> POSVersions { get; set; }
        public virtual DbSet<RewardCodeSend> RewardCodeSends { get; set; }
        public virtual DbSet<SignalStore> SignalStores { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<StoreNoMapping> StoreNoMappings { get; set; }

    }
}
