//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.POSBLUE.Data.DataBaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CpnVchBOMHeader
    {
        public string ItemNo { get; set; }
        public string ItemName { get; set; }
        public string UnitOfMeasure { get; set; }
        public int DiscountType { get; set; }
        public decimal DiscountValue { get; set; }
        public decimal MaxAmount { get; set; }
        public string ArticleType { get; set; }
        public decimal ValueOfVoucher { get; set; }
        public System.DateTime StartingDate { get; set; }
        public System.DateTime EndingDate { get; set; }
        public byte Blocked { get; set; }
        public string CouponCode { get; set; }
        public int LimitQty { get; set; }
        public System.DateTime LastDateModified { get; set; }
        public Nullable<long> Counter { get; set; }
        public Nullable<bool> IsCheckItem { get; set; }
        public string Pkey { get; set; }
        public string IssueType { get; set; }
        public Nullable<double> MinAmount { get; set; }
        public string Company { get; set; }
        public string RefKey1 { get; set; }
        public string RefKey2 { get; set; }
        public string RefKey3 { get; set; }
        public string RefKey4 { get; set; }
        public string RefKey5 { get; set; }
        public Nullable<bool> IsMultiUse { get; set; }
        public Nullable<int> LimitQtyUsed { get; set; }
        public string CpnVchType { get; set; }
        public Nullable<bool> IsCheckAPI { get; set; }
        public string SaleType { get; set; }
        public string StoreGroupCode { get; set; }
    }
}
