//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.POSBLUE.Data.DataBaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CX_ExtraItemBill
    {
        public long ID { get; set; }
        public string ReceiptNumber { get; set; }
        public Nullable<double> RecordNo { get; set; }
        public string Barcode { get; set; }
        public string Article { get; set; }
        public string ArticleName { get; set; }
        public string UOM { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> RefundQuantity { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<double> LineAmount { get; set; }
        public Nullable<double> ExtraQuantityEarn { get; set; }
        public Nullable<double> ExtraAmountEarn { get; set; }
        public Nullable<double> ExtraQuantityRefund { get; set; }
        public Nullable<double> ExtraAmountRefund { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUser { get; set; }
    }
}
