//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.POSBLUE.Data.DataBaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogService
    {
        public long ID { get; set; }
        public string StoreNo { get; set; }
        public string PosTerminal { get; set; }
        public string RequestPOS { get; set; }
        public string RequestPartner { get; set; }
        public string ResponsPOS { get; set; }
        public string ResponsePartner { get; set; }
        public string EndPointPartner { get; set; }
        public string MethodPartner { get; set; }
        public string ActionController { get; set; }
        public Nullable<int> TimeResponse { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
