//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.POSBLUE.Data.DataBaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSGiftInfo
    {
        public string GiftCode { get; set; }
        public string GiftType { get; set; }
        public int GiftValue { get; set; }
        public string GiftStatus { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string PosCreated { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string PosUsed { get; set; }
        public Nullable<System.DateTime> UsedTime { get; set; }
    }
}
