//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.POSBLUE.Data.DataBaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewardCodeSend
    {
        public long ID { get; set; }
        public string StoreNo { get; set; }
        public string PosID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string OrderNo { get; set; }
        public string OfferNo { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string IPServer { get; set; }
    }
}
