//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.POSBLUE.Data.DataBaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreSetServer
    {
        public string StoreNo { get; set; }
        public string ServerIP { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Status { get; set; }
        public string ServerRead { get; set; }
    }
}
