//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.POSBLUE.Data.DataBaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncFileLog
    {
        public int ID { get; set; }
        public string FileName { get; set; }
        public string TableName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Folder { get; set; }
        public Nullable<short> Status { get; set; }
        public string ErrorMsg { get; set; }
        public string SyncType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
