//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.POSBLUE.Data.DataBaseContext.PLG
{
    using System;
    using System.Collections.Generic;
    
    public partial class PL_VoucherCard
    {
        public long ID { get; set; }
        public string CardType { get; set; }
        public string SeriNo { get; set; }
        public string CardNo { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public Nullable<int> ValidDays { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<double> RemainValue { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsReset { get; set; }
        public string ResetTime { get; set; }
        public Nullable<System.DateTime> ActivateDate { get; set; }
        public string LastUsedStore { get; set; }
        public string LastUsedPosID { get; set; }
        public Nullable<System.DateTime> LastUsedDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UserName { get; set; }
    }
}
