//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.POSBLUE.Data.DataBaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogCommon
    {
        public long ID { get; set; }
        public string StoreNo { get; set; }
        public string POSTerminal { get; set; }
        public string OrderNo { get; set; }
        public string CardNumber { get; set; }
        public string ActionType { get; set; }
        public string JSONModel { get; set; }
        public string MessageError { get; set; }
        public string IPServer { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
