//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.POSBLUE.Data.DataBaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSVersion
    {
        public string LastVersion { get; set; }
        public string CurVersion { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<long> Counter { get; set; }
        public string Source { get; set; }
        public string Pkey { get; set; }
        public Nullable<bool> IsUpdate { get; set; }
        public string Folder { get; set; }
    }
}
