//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.POSBLUE.Data.DataBaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreMapping
    {
        public int ID { get; set; }
        public string OldTerminalID { get; set; }
        public string OldStoreID { get; set; }
        public string OldVinPayTerminalID { get; set; }
        public string OldVinPayStoreID { get; set; }
        public string NewTerminalID { get; set; }
        public string NewStoreID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
