//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.POSBLUE.API.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"http://dev-po01.masan.local:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=TP_WebService&receiverParty=&receiverService=&interface=VoucherSerialNo&interfaceNamespace=urn%3AVincommerce%3ANECPOS%3ASD%3ANECPOS%3AVoucherSerialNo%3ATo%3ASAPECC%3AVoucherSerialNo%3AAck")]
        public string VCM_POSBLUE_API_SAPReturnVoucher_VoucherSerialNoService {
            get {
                return ((string)(this["VCM_POSBLUE_API_SAPReturnVoucher_VoucherSerialNoService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"http://dev-po01.masan.local:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=TP_WebService&receiverParty=&receiverService=&interface=SI_VoucherSerialNo_OUT&interfaceNamespace=urn%3AVincommerce%3ANECPOS%3ASD%3ANECPOS%3AVoucherSerialNo%3ATo%3ASAPECC%3AVoucherSerialNo%3AU2829")]
        public string VCM_POSBLUE_API_SAPVoucher_SI_VoucherSerialNo_OUTService {
            get {
                return ((string)(this["VCM_POSBLUE_API_SAPVoucher_SI_VoucherSerialNo_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.111.55.147:7007/OneFlexiAxisService/services/OneFlexiAxisService.OneFle" +
            "xiAxisServiceHttpSoap11Endpoint/")]
        public string VCM_POSBLUE_API_OneFlexiAxisService_OneFlexiAxisService {
            get {
                return ((string)(this["VCM_POSBLUE_API_OneFlexiAxisService_OneFlexiAxisService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pl-devqas-po.asia-southeast1-b.c.pl-dev-saperp.internal:50000/XISOAPAdapte" +
            "r/MessageServlet?senderParty=&senderService=BS_ODOO&receiverParty=&receiverServi" +
            "ce=&interface=SI_VC_OUT&interfaceNamespace=urn%3Aphuclong%3As4%3Avoucher%3Ato%3A" +
            "odoo%3Aws")]
        public string VCM_POSBLUE_API_SAPOdoo_SI_VC_OUTService {
            get {
                return ((string)(this["VCM_POSBLUE_API_SAPOdoo_SI_VC_OUTService"]));
            }
        }
    }
}
