//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace VCM.POSBLUE.API.SAPReturnVoucher {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="VoucherSerialNoBinding", Namespace="urn:Vincommerce:NECPOS:SD:NECPOS:VoucherSerialNo:To:SAPECC:VoucherSerialNo:Ack")]
    public partial class VoucherSerialNoService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback VoucherSerialNoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public VoucherSerialNoService() {
            this.Url = global::VCM.POSBLUE.API.Properties.Settings.Default.VCM_POSBLUE_API_SAPReturnVoucher_VoucherSerialNoService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event VoucherSerialNoCompletedEventHandler VoucherSerialNoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("VoucherSerialNo_Output", Namespace="urn:Vincommerce:NECPOS:SD:NECPOS:VoucherSerialNo:To:SAPECC:VoucherSerialNo:Ack")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Output", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public VoucherSerialNo_OutputOutput[] VoucherSerialNo([System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:Vincommerce:NECPOS:SD:NECPOS:VoucherSerialNo:To:SAPECC:VoucherSerialNo:Ack")] [System.Xml.Serialization.XmlArrayItemAttribute("Input", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] VoucherSerialNo_InputInput[] VoucherSerialNo_Input) {
            object[] results = this.Invoke("VoucherSerialNo", new object[] {
                        VoucherSerialNo_Input});
            return ((VoucherSerialNo_OutputOutput[])(results[0]));
        }
        
        /// <remarks/>
        public void VoucherSerialNoAsync(VoucherSerialNo_InputInput[] VoucherSerialNo_Input) {
            this.VoucherSerialNoAsync(VoucherSerialNo_Input, null);
        }
        
        /// <remarks/>
        public void VoucherSerialNoAsync(VoucherSerialNo_InputInput[] VoucherSerialNo_Input, object userState) {
            if ((this.VoucherSerialNoOperationCompleted == null)) {
                this.VoucherSerialNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoucherSerialNoOperationCompleted);
            }
            this.InvokeAsync("VoucherSerialNo", new object[] {
                        VoucherSerialNo_Input}, this.VoucherSerialNoOperationCompleted, userState);
        }
        
        private void OnVoucherSerialNoOperationCompleted(object arg) {
            if ((this.VoucherSerialNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoucherSerialNoCompleted(this, new VoucherSerialNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Vincommerce:NECPOS:SD:NECPOS:VoucherSerialNo:To:SAPECC:VoucherSerialNo:Ack")]
    public partial class VoucherSerialNo_InputInput {
        
        private string voucher_TypeField;
        
        private string article_NoField;
        
        private string serialNoField;
        
        private string voucher_ValueField;
        
        private string voucher_CurrencyField;
        
        private string validity_From_DateField;
        
        private string expiry_DateField;
        
        private string processing_TypeField;
        
        private string statusField;
        
        private string siteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Voucher_Type {
            get {
                return this.voucher_TypeField;
            }
            set {
                this.voucher_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Article_No {
            get {
                return this.article_NoField;
            }
            set {
                this.article_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SerialNo {
            get {
                return this.serialNoField;
            }
            set {
                this.serialNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Voucher_Value {
            get {
                return this.voucher_ValueField;
            }
            set {
                this.voucher_ValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Voucher_Currency {
            get {
                return this.voucher_CurrencyField;
            }
            set {
                this.voucher_CurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Validity_From_Date {
            get {
                return this.validity_From_DateField;
            }
            set {
                this.validity_From_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Expiry_Date {
            get {
                return this.expiry_DateField;
            }
            set {
                this.expiry_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Processing_Type {
            get {
                return this.processing_TypeField;
            }
            set {
                this.processing_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Vincommerce:NECPOS:SD:NECPOS:VoucherSerialNo:To:SAPECC:VoucherSerialNo:Ack")]
    public partial class VoucherSerialNo_OutputOutput {
        
        private string statusField;
        
        private string returnField;
        
        private string article_NoField;
        
        private string voucher_ValueField;
        
        private string voucher_CurrencyField;
        
        private string validity_From_DateField;
        
        private string expiry_DateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Article_No {
            get {
                return this.article_NoField;
            }
            set {
                this.article_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Voucher_Value {
            get {
                return this.voucher_ValueField;
            }
            set {
                this.voucher_ValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Voucher_Currency {
            get {
                return this.voucher_CurrencyField;
            }
            set {
                this.voucher_CurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Validity_From_Date {
            get {
                return this.validity_From_DateField;
            }
            set {
                this.validity_From_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Expiry_Date {
            get {
                return this.expiry_DateField;
            }
            set {
                this.expiry_DateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void VoucherSerialNoCompletedEventHandler(object sender, VoucherSerialNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoucherSerialNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoucherSerialNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VoucherSerialNo_OutputOutput[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VoucherSerialNo_OutputOutput[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591