//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace VCM.POSBLUE.API.SAPVoucher {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_VoucherSerialNo_OUTBinding", Namespace="urn:Vincommerce:NECPOS:SD:NECPOS:VoucherSerialNo:To:SAPECC:VoucherSerialNo:U2829")]
    public partial class SI_VoucherSerialNo_OUTService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_NECPOS_Validation_PCardOperationCompleted;
        
        private System.Threading.SendOrPostCallback SI_VoucherSerialNo_OUTOperationCompleted;
        
        private System.Threading.SendOrPostCallback SI_VoucherCoupon_RequestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_VoucherSerialNo_OUTService() {
            this.Url = global::VCM.POSBLUE.API.Properties.Settings.Default.VCM_POSBLUE_API_SAPVoucher_SI_VoucherSerialNo_OUTService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_NECPOS_Validation_PCardCompletedEventHandler SI_NECPOS_Validation_PCardCompleted;
        
        /// <remarks/>
        public event SI_VoucherSerialNo_OUTCompletedEventHandler SI_VoucherSerialNo_OUTCompleted;
        
        /// <remarks/>
        public event SI_VoucherCoupon_RequestCompletedEventHandler SI_VoucherCoupon_RequestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("MT_NECPOS_ValidationPCard_Reponse", Namespace="urn:Vincommerce:NECPOS:SD:NECPOS:VoucherSerialNo:To:SAPECC:VoucherSerialNo:U2829")]
        public DT_NECPOS_ValidationPCard_Response SI_NECPOS_Validation_PCard([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:Vincommerce:NECPOS:SD:NECPOS:VoucherSerialNo:To:SAPECC:VoucherSerialNo:U2829")] DT_NECPOS_ValidationPCard_Request MT_NECPOS_ValidationPCard_Request) {
            object[] results = this.Invoke("SI_NECPOS_Validation_PCard", new object[] {
                        MT_NECPOS_ValidationPCard_Request});
            return ((DT_NECPOS_ValidationPCard_Response)(results[0]));
        }
        
        /// <remarks/>
        public void SI_NECPOS_Validation_PCardAsync(DT_NECPOS_ValidationPCard_Request MT_NECPOS_ValidationPCard_Request) {
            this.SI_NECPOS_Validation_PCardAsync(MT_NECPOS_ValidationPCard_Request, null);
        }
        
        /// <remarks/>
        public void SI_NECPOS_Validation_PCardAsync(DT_NECPOS_ValidationPCard_Request MT_NECPOS_ValidationPCard_Request, object userState) {
            if ((this.SI_NECPOS_Validation_PCardOperationCompleted == null)) {
                this.SI_NECPOS_Validation_PCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_NECPOS_Validation_PCardOperationCompleted);
            }
            this.InvokeAsync("SI_NECPOS_Validation_PCard", new object[] {
                        MT_NECPOS_ValidationPCard_Request}, this.SI_NECPOS_Validation_PCardOperationCompleted, userState);
        }
        
        private void OnSI_NECPOS_Validation_PCardOperationCompleted(object arg) {
            if ((this.SI_NECPOS_Validation_PCardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_NECPOS_Validation_PCardCompleted(this, new SI_NECPOS_Validation_PCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("MT_NECPOS_VoucherSerialNo_Output", Namespace="urn:Vincommerce:NECPOS:SD:NECPOS:VoucherSerialNo:To:SAPECC:VoucherSerialNo:U2829")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Output", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_NECPOS_VoucherSerialNo_OutputOutput[] SI_VoucherSerialNo_OUT([System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:Vincommerce:NECPOS:SD:NECPOS:VoucherSerialNo:To:SAPECC:VoucherSerialNo:U2829")] [System.Xml.Serialization.XmlArrayItemAttribute("Input", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] DT_NECPOS_VoucherSerialNo_InputInput[] MT_NECPOS_VoucherSerialNo_Input) {
            object[] results = this.Invoke("SI_VoucherSerialNo_OUT", new object[] {
                        MT_NECPOS_VoucherSerialNo_Input});
            return ((DT_NECPOS_VoucherSerialNo_OutputOutput[])(results[0]));
        }
        
        /// <remarks/>
        public void SI_VoucherSerialNo_OUTAsync(DT_NECPOS_VoucherSerialNo_InputInput[] MT_NECPOS_VoucherSerialNo_Input) {
            this.SI_VoucherSerialNo_OUTAsync(MT_NECPOS_VoucherSerialNo_Input, null);
        }
        
        /// <remarks/>
        public void SI_VoucherSerialNo_OUTAsync(DT_NECPOS_VoucherSerialNo_InputInput[] MT_NECPOS_VoucherSerialNo_Input, object userState) {
            if ((this.SI_VoucherSerialNo_OUTOperationCompleted == null)) {
                this.SI_VoucherSerialNo_OUTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_VoucherSerialNo_OUTOperationCompleted);
            }
            this.InvokeAsync("SI_VoucherSerialNo_OUT", new object[] {
                        MT_NECPOS_VoucherSerialNo_Input}, this.SI_VoucherSerialNo_OUTOperationCompleted, userState);
        }
        
        private void OnSI_VoucherSerialNo_OUTOperationCompleted(object arg) {
            if ((this.SI_VoucherSerialNo_OUTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_VoucherSerialNo_OUTCompleted(this, new SI_VoucherSerialNo_OUTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("MT_NECPOS_VoucherCoupon_Response", Namespace="urn:Vincommerce:NECPOS:SD:NECPOS:VoucherSerialNo:To:SAPECC:VoucherSerialNo:U2829")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Output", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_VINID_VoucherCouponOutput[] SI_VoucherCoupon_Request([System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:Vincommerce:NECPOS:SD:NECPOS:VoucherSerialNo:To:SAPECC:VoucherSerialNo:U2829")] [System.Xml.Serialization.XmlArrayItemAttribute("Input", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] DT_NECPOS_VoucherCouponInput[] MT_NECPOS_VoucherCoupon_Request) {
            object[] results = this.Invoke("SI_VoucherCoupon_Request", new object[] {
                        MT_NECPOS_VoucherCoupon_Request});
            return ((DT_VINID_VoucherCouponOutput[])(results[0]));
        }
        
        /// <remarks/>
        public void SI_VoucherCoupon_RequestAsync(DT_NECPOS_VoucherCouponInput[] MT_NECPOS_VoucherCoupon_Request) {
            this.SI_VoucherCoupon_RequestAsync(MT_NECPOS_VoucherCoupon_Request, null);
        }
        
        /// <remarks/>
        public void SI_VoucherCoupon_RequestAsync(DT_NECPOS_VoucherCouponInput[] MT_NECPOS_VoucherCoupon_Request, object userState) {
            if ((this.SI_VoucherCoupon_RequestOperationCompleted == null)) {
                this.SI_VoucherCoupon_RequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_VoucherCoupon_RequestOperationCompleted);
            }
            this.InvokeAsync("SI_VoucherCoupon_Request", new object[] {
                        MT_NECPOS_VoucherCoupon_Request}, this.SI_VoucherCoupon_RequestOperationCompleted, userState);
        }
        
        private void OnSI_VoucherCoupon_RequestOperationCompleted(object arg) {
            if ((this.SI_VoucherCoupon_RequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_VoucherCoupon_RequestCompleted(this, new SI_VoucherCoupon_RequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Vincommerce:NECPOS:SD:NECPOS:VoucherSerialNo:To:SAPECC:VoucherSerialNo:U2829")]
    public partial class DT_NECPOS_ValidationPCard_Request {
        
        private string physicalCardNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PhysicalCardNumber {
            get {
                return this.physicalCardNumberField;
            }
            set {
                this.physicalCardNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Vincommerce:NECPOS:SD:NECPOS:VoucherSerialNo:To:SAPECC:VoucherSerialNo:U2829")]
    public partial class DT_NECPOS_ValidationPCard_Response {
        
        private string serialNoField;
        
        private string statusField;
        
        private string returnField;
        
        private string articleNumberField;
        
        private string voucherValueField;
        
        private string voucherCurrencyField;
        
        private string validityFromDateField;
        
        private string expiryDateField;
        
        private string articleTpyeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SerialNo {
            get {
                return this.serialNoField;
            }
            set {
                this.serialNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ArticleNumber {
            get {
                return this.articleNumberField;
            }
            set {
                this.articleNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VoucherValue {
            get {
                return this.voucherValueField;
            }
            set {
                this.voucherValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VoucherCurrency {
            get {
                return this.voucherCurrencyField;
            }
            set {
                this.voucherCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ValidityFromDate {
            get {
                return this.validityFromDateField;
            }
            set {
                this.validityFromDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ExpiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ArticleTpye {
            get {
                return this.articleTpyeField;
            }
            set {
                this.articleTpyeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Vincommerce:NECPOS:SD:NECPOS:VoucherSerialNo:To:SAPECC:VoucherSerialNo:U2829")]
    public partial class DT_NECPOS_VoucherSerialNo_InputInput {
        
        private string voucher_TypeField;
        
        private string serialNoField;
        
        private string voucher_ValueField;
        
        private string voucher_CurrencyField;
        
        private string validity_From_DateField;
        
        private string expiry_DateField;
        
        private string processing_TypeField;
        
        private string statusField;
        
        private string siteField;
        
        private string article_NoField;
        
        private string bonus_BuyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Voucher_Type {
            get {
                return this.voucher_TypeField;
            }
            set {
                this.voucher_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SerialNo {
            get {
                return this.serialNoField;
            }
            set {
                this.serialNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Voucher_Value {
            get {
                return this.voucher_ValueField;
            }
            set {
                this.voucher_ValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Voucher_Currency {
            get {
                return this.voucher_CurrencyField;
            }
            set {
                this.voucher_CurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Validity_From_Date {
            get {
                return this.validity_From_DateField;
            }
            set {
                this.validity_From_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Expiry_Date {
            get {
                return this.expiry_DateField;
            }
            set {
                this.expiry_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Processing_Type {
            get {
                return this.processing_TypeField;
            }
            set {
                this.processing_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Article_No {
            get {
                return this.article_NoField;
            }
            set {
                this.article_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Bonus_Buy {
            get {
                return this.bonus_BuyField;
            }
            set {
                this.bonus_BuyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Vincommerce:NECPOS:SD:NECPOS:VoucherSerialNo:To:SAPECC:VoucherSerialNo:U2829")]
    public partial class DT_NECPOS_VoucherSerialNo_OutputOutput {
        
        private string statusField;
        
        private string returnField;
        
        private string article_NoField;
        
        private string article_TypeField;
        
        private string voucher_ValueField;
        
        private string voucher_CurrencyField;
        
        private string validity_From_DateField;
        
        private string expiry_DateField;
        
        private string companyCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Article_No {
            get {
                return this.article_NoField;
            }
            set {
                this.article_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Article_Type {
            get {
                return this.article_TypeField;
            }
            set {
                this.article_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Voucher_Value {
            get {
                return this.voucher_ValueField;
            }
            set {
                this.voucher_ValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Voucher_Currency {
            get {
                return this.voucher_CurrencyField;
            }
            set {
                this.voucher_CurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Validity_From_Date {
            get {
                return this.validity_From_DateField;
            }
            set {
                this.validity_From_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Expiry_Date {
            get {
                return this.expiry_DateField;
            }
            set {
                this.expiry_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Vincommerce:NECPOS:SD:NECPOS:VoucherSerialNo:To:SAPECC:VoucherSerialNo:U2829")]
    public partial class DT_NECPOS_VoucherCouponInput {
        
        private string cSNField;
        
        private string serialNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CSN {
            get {
                return this.cSNField;
            }
            set {
                this.cSNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SerialNo {
            get {
                return this.serialNoField;
            }
            set {
                this.serialNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Vincommerce:NECPOS:SD:NECPOS:VoucherSerialNo:To:SAPECC:VoucherSerialNo:U2829")]
    public partial class DT_VINID_VoucherCouponOutput {
        
        private string cSNField;
        
        private string serialNoField;
        
        private string articleNoField;
        
        private string amountField;
        
        private string validFromField;
        
        private string validToField;
        
        private string descriptionField;
        
        private string typeField;
        
        private string returnField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CSN {
            get {
                return this.cSNField;
            }
            set {
                this.cSNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SerialNo {
            get {
                return this.serialNoField;
            }
            set {
                this.serialNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ArticleNo {
            get {
                return this.articleNoField;
            }
            set {
                this.articleNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ValidFrom {
            get {
                return this.validFromField;
            }
            set {
                this.validFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ValidTo {
            get {
                return this.validToField;
            }
            set {
                this.validToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SI_NECPOS_Validation_PCardCompletedEventHandler(object sender, SI_NECPOS_Validation_PCardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_NECPOS_Validation_PCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SI_NECPOS_Validation_PCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_NECPOS_ValidationPCard_Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_NECPOS_ValidationPCard_Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SI_VoucherSerialNo_OUTCompletedEventHandler(object sender, SI_VoucherSerialNo_OUTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_VoucherSerialNo_OUTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SI_VoucherSerialNo_OUTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_NECPOS_VoucherSerialNo_OutputOutput[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_NECPOS_VoucherSerialNo_OutputOutput[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SI_VoucherCoupon_RequestCompletedEventHandler(object sender, SI_VoucherCoupon_RequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_VoucherCoupon_RequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SI_VoucherCoupon_RequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_VINID_VoucherCouponOutput[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_VINID_VoucherCouponOutput[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591