//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.PLG
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PLGContainer : DbContext
    {
        public PLGContainer()
            : base("name=PLGContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<PLGEODCreatedInvoice> PLGEODCreatedInvoices { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<StoreNoseriVAT> StoreNoseriVATs { get; set; }
        public virtual DbSet<VatNumber> VatNumbers { get; set; }
    }
}
