//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.PLG
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLGEODCreatedInvoice
    {
        public int ID { get; set; }
        public string BusinessDateCode { get; set; }
        public Nullable<System.DateTime> BusinessDate { get; set; }
        public string StoreNo { get; set; }
        public string Key { get; set; }
        public string DocumentNo { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> VATRate { get; set; }
        public string ObjID { get; set; }
    }
}
