//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.PLG
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreNoseriVAT
    {
        public int ID { get; set; }
        public string StoreNo { get; set; }
        public string ObjectID { get; set; }
        public string StoreName { get; set; }
        public string BranchNo { get; set; }
        public string NoseriCode { get; set; }
        public string InvoiceType { get; set; }
        public string CustNameDefault { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
