//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.PLG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public string AppCode { get; set; }
        public string StoreNo { get; set; }
        public string ObjectID { get; set; }
        public string StoreName { get; set; }
        public string RegionCode { get; set; }
        public bool Blocked { get; set; }
        public int Id { get; set; }
        public System.DateTime CrtDate { get; set; }
    }
}
