//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Loyalty
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchFileLog
    {
        public int ID { get; set; }
        public string FileName { get; set; }
        public Nullable<int> TotalRecord { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public string Error { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ProcessID { get; set; }
    }
}
