//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Loyalty
{
    using System;
    using System.Collections.Generic;
    
    public partial class CX_ExtraHeader
    {
        public long ID { get; set; }
        public string StoreNo { get; set; }
        public string POSCode { get; set; }
        public string OrderNo { get; set; }
        public string TransactionType { get; set; }
        public Nullable<double> TransactionTime { get; set; }
        public string CustomerName { get; set; }
        public string CardNumber { get; set; }
        public string PhoneNUmber { get; set; }
        public Nullable<double> TotalBillAmount { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<bool> OverQuota { get; set; }
        public Nullable<double> ExtraEarnByItems { get; set; }
        public Nullable<double> ExtraEarnByCampaign { get; set; }
        public Nullable<double> ExtraRefundByItems { get; set; }
        public Nullable<double> ExtraRefundByCampaign { get; set; }
        public string EmployeeCode { get; set; }
        public string CompanyCode { get; set; }
        public string OriginalReceiptNumber { get; set; }
        public string OriginalPosNumber { get; set; }
        public string OriginalReferenceNumber { get; set; }
        public Nullable<double> EarnByDefault { get; set; }
        public Nullable<double> RefundAmount { get; set; }
        public Nullable<double> RefundPointDefault { get; set; }
        public Nullable<double> Rate { get; set; }
        public string ActionAPI { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUser { get; set; }
    }
}
