//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Loyalty
{
    using System;
    using System.Collections.Generic;
    
    public partial class CX_LogAPI
    {
        public long ID { get; set; }
        public string StoreNo { get; set; }
        public string POSTerminal { get; set; }
        public string CardNumber { get; set; }
        public string InvoiceNo { get; set; }
        public string ActionType { get; set; }
        public string PlainText { get; set; }
        public string Signature { get; set; }
        public string RequestPOS { get; set; }
        public string RequestXML { get; set; }
        public string ResponseXML { get; set; }
        public Nullable<int> ResponseTotal { get; set; }
        public string Source { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
