//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Loyalty
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogSAP
    {
        public long ID { get; set; }
        public string StoreNo { get; set; }
        public string POSTerminal { get; set; }
        public string VoucherNumber { get; set; }
        public string RequestPOS { get; set; }
        public string RequestSAP { get; set; }
        public string ResponseSAP { get; set; }
        public string ActionType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
