//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.Loyalty
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LoyaltyContainer : DbContext
    {
        public LoyaltyContainer()
            : base("name=LoyaltyContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BatchFileLog> BatchFileLogs { get; set; }
        public virtual DbSet<ExtraHeader> ExtraHeaders { get; set; }
        public virtual DbSet<ExtraItemBill> ExtraItemBills { get; set; }
        public virtual DbSet<LogAPI> LogAPIs { get; set; }
        public virtual DbSet<LogSAP> LogSAPs { get; set; }
        public virtual DbSet<CX_ExtraHeader> CX_ExtraHeader { get; set; }
        public virtual DbSet<CX_ExtraItemBill> CX_ExtraItemBill { get; set; }
        public virtual DbSet<CX_LogAPI> CX_LogAPI { get; set; }
        public virtual DbSet<CX_TransactionLoyalty> CX_TransactionLoyalty { get; set; }
    }
}
