//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.POSBLUE.Data.DataBaseContext.SaleStaging
{
    using System;
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CentralSaleStagingContainer : DbContext
    {
        public static string setDB1 = @"" + ConfigurationManager.AppSettings["setDB1"];
        public static string setDB2 = @"" + ConfigurationManager.AppSettings["setDB2"];
        public static string setDB3 = @"" + ConfigurationManager.AppSettings["setDB3"];
        public static string setDB4 = @"" + ConfigurationManager.AppSettings["setDB4"];
        public static string setDB5 = @"" + ConfigurationManager.AppSettings["setDB5"];
        public CentralSaleStagingContainer()
            : base("name=CentralSaleStagingContainer")
        {
        }
        public CentralSaleStagingContainer(string IPServer)
           : base("name=" + (IPServer == setDB1 ? "SetDB1_SalesStaging"
                 : (IPServer == setDB2 ? "SetDB2_SalesStaging"
                 : (IPServer == setDB3 ? "SetDB3_SalesStaging"
                 : (IPServer == setDB4 ? "SetDB4_SalesStaging"
                 : (IPServer == setDB5 ? "SetDB5_SalesStaging"
                 : ""))))))
        {

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TransHeaderOrig> TransHeaderOrigs { get; set; }
        public virtual DbSet<TransLineOrig> TransLineOrigs { get; set; }
        public virtual DbSet<TransBluePointOrig> TransBluePointOrigs { get; set; }
        public virtual DbSet<TransHeaderStaging> TransHeaderStagings { get; set; }
        public virtual DbSet<TransDiscountEntry> TransDiscountEntries { get; set; }
        public virtual DbSet<TransPaymentEntry> TransPaymentEntries { get; set; }
    }
}
