//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.POSBLUE.Data.DataBaseContext.SaleStaging
{
    using System;
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KIOSContainer : DbContext
    {
        public static string setDB1 = @"" + ConfigurationManager.AppSettings["setDB1"];
        public static string setDB2 = @"" + ConfigurationManager.AppSettings["setDB2"];
        public static string setDB3 = @"" + ConfigurationManager.AppSettings["setDB3"];
        public static string setDB4 = @"" + ConfigurationManager.AppSettings["setDB4"];
        public static string setDB5 = @"" + ConfigurationManager.AppSettings["setDB5"];
        public KIOSContainer()
            : base("name=KIOSContainer")
        {
        }

        public KIOSContainer(string IPServer)
      : base("name=" + (IPServer == setDB1 ? "SetDB1_KIOSContainer"
            : (IPServer == setDB2 ? "SetDB2_KIOSContainer"
            : (IPServer == setDB3 ? "SetDB3_KIOSContainer"
            : (IPServer == setDB4 ? "SetDB4_KIOSContainer"
            : (IPServer == setDB5 ? "SetDB5_KIOSContainer"
            : ""))))))
        {

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LogSaleKio> LogSaleKios { get; set; }
    }
}
