//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.POSBLUE.Data.DataBaseContext.SaleStaging
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransLineOrig
    {
        public long ID { get; set; }
        public int LineNo { get; set; }
        public string DocumentNo { get; set; }
        public Nullable<int> LineType { get; set; }
        public string LocationCode { get; set; }
        public string ItemNo { get; set; }
        public string Description { get; set; }
        public string UnitOfMeasure { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> OfferUnitPrice { get; set; }
        public Nullable<double> AmountBeforeDiscount { get; set; }
        public Nullable<double> DiscountPercent { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<double> VATPercent { get; set; }
        public Nullable<double> VATAmount { get; set; }
        public Nullable<double> LineAmountIncVAT { get; set; }
        public string OfferNo { get; set; }
        public Nullable<int> DiscountType { get; set; }
        public Nullable<double> TriggerQuantity { get; set; }
        public string StaffID { get; set; }
        public Nullable<double> PrepaymentAmount { get; set; }
        public string VATCode { get; set; }
        public Nullable<int> DeliveringMethod { get; set; }
        public string Barcode { get; set; }
        public Nullable<double> OrderDiscountPercent { get; set; }
        public Nullable<double> OrderDiscountAmount { get; set; }
        public string DivisionCode { get; set; }
        public string CategoryCode { get; set; }
        public string ProductGroupCode { get; set; }
        public Nullable<byte> BlockedMemberPoint { get; set; }
        public string SerialNo { get; set; }
        public string OrigTransStore { get; set; }
        public string OrigTransPos { get; set; }
        public Nullable<int> OrigTransNo { get; set; }
        public Nullable<int> OrigTransLineNo { get; set; }
        public string OrigOrderNo { get; set; }
        public Nullable<int> OrigLineNumber { get; set; }
        public Nullable<byte> BlockedPromotion { get; set; }
        public string Infocodes { get; set; }
        public Nullable<double> MemberPointsEarn { get; set; }
        public Nullable<double> ReturnedQuantity { get; set; }
        public Nullable<double> DeliveryQuantity { get; set; }
        public Nullable<int> DeliveryStatus { get; set; }
        public Nullable<double> MemberPointsRedeem { get; set; }
        public string VariantNo { get; set; }
        public string LotNo { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<double> AmountCalPoint { get; set; }
        public string WaitingListNo { get; set; }
        public string ArticleType { get; set; }
        public Nullable<System.DateTime> ScanTime { get; set; }
        public string DiscountCode { get; set; }
        public string PromotionGroup { get; set; }
        public Nullable<long> Counter { get; set; }
        public Nullable<int> LineNoEffect { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<double> DiscountQuantity { get; set; }
        public Nullable<double> DiscountUnit { get; set; }
        public Nullable<int> SnGLineID { get; set; }
        public Nullable<double> QtyDiscount { get; set; }
        public Nullable<double> QtyDiscountReturned { get; set; }
    }
}
