//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.POSBLUE.Data.DataBaseContext.CentralSale
{
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class CentralSaleContainer : DbContext
    {
        public static string setDB1 = @"" + ConfigurationManager.AppSettings["setDB1"];
        public static string setDB2 = @"" + ConfigurationManager.AppSettings["setDB2"];
        public static string setDB3 = @"" + ConfigurationManager.AppSettings["setDB3"];
        public static string setDB4 = @"" + ConfigurationManager.AppSettings["setDB4"];
        public static string setDB5 = @"" + ConfigurationManager.AppSettings["setDB5"];
        public static string setDB6 = @"" + ConfigurationManager.AppSettings["setDB6"];
        public static string setDB7 = @"" + ConfigurationManager.AppSettings["setDB7"];
        public static string setDB8 = @"" + ConfigurationManager.AppSettings["setDB8"];
        public static string setDB9 = @"" + ConfigurationManager.AppSettings["setDB9"];
        public static string setDB10 = @"" + ConfigurationManager.AppSettings["setDB10"];
        public CentralSaleContainer()
            : base("name=CentralSaleContainer")
        {
        }
        public CentralSaleContainer(string IPServer): base("name=" + (IPServer == setDB1 ? "SetDB1_CentralSale"
             : (IPServer == setDB2 ? "SetDB2_CentralSale"
             : (IPServer == setDB3 ? "SetDB3_CentralSale"
             : (IPServer == setDB4 ? "SetDB4_CentralSale"
             : (IPServer == setDB5 ? "SetDB5_CentralSale"
             : (IPServer == setDB6 ? "SetDB6_CentralSale"
             : (IPServer == setDB7 ? "SetDB7_CentralSale"
             : (IPServer == setDB8 ? "SetDB8_CentralSale"
             : (IPServer == setDB9 ? "SetDB9_CentralSale"
             : (IPServer == setDB10 ? "SetDB10_CentralSale"
             : "")))))))))))
        {

        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<BussinessDateOpen> BussinessDateOpens { get; set; }
        public virtual DbSet<POSEOD_API> POSEOD_API { get; set; }
        public virtual DbSet<TransHeader> TransHeaders { get; set; }
        public virtual DbSet<TransCpnVchIssue> TransCpnVchIssues { get; set; }

    }
}
