//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.POSBLUE.Data.DataBaseContext.CentralSale
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSEOD_API
    {
        public int ID { get; set; }
        public string POSTerminal { get; set; }
        public string StoreNo { get; set; }
        public Nullable<System.DateTime> BussinessDate { get; set; }
        public Nullable<int> TotalSale { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
