//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.PartnerMD
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeeFood_notify_new_order
    {
        public long order_id { get; set; }
        public int restaurant_id { get; set; }
        public string partner_restaurant_id { get; set; }
        public int status { get; set; }
        public bool is_pick_up_order { get; set; }
        public int remaining_time { get; set; }
        public string delivery_address { get; set; }
        public int order_amount { get; set; }
        public string customer_name { get; set; }
        public System.DateTime created_at { get; set; }
        public string delivery_note { get; set; }
        public string order_items { get; set; }
        public string flag_update { get; set; }
        public string status_message { get; set; }
        public System.DateTime updated_time { get; set; }
        public System.DateTime created_time { get; set; }
    }
}
