//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.PartnerMD
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeeFood_restaurant
    {
        public string restaurant_id { get; set; }
        public string partner_restaurant_id { get; set; }
        public string restaurant_name { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public string foody_service { get; set; }
        public Nullable<System.DateTime> crt_date { get; set; }
        public Nullable<bool> is_header { get; set; }
        public string parent_restaurant { get; set; }
        public Nullable<bool> blocked { get; set; }
        public string CrtUser { get; set; }
        public Nullable<System.DateTime> CrtDate { get; set; }
        public string ChgUser { get; set; }
        public Nullable<System.DateTime> ChgDate { get; set; }
    }
}
