//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.PartnerMD
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeeFood_modifier_group_name
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string AvailableStatus { get; set; }
        public string CrtUser { get; set; }
        public System.DateTime CrtDate { get; set; }
        public string ChgUser { get; set; }
        public System.DateTime ChgDate { get; set; }
        public int SelectionRangeMin { get; set; }
        public int SelectionRangeMax { get; set; }
        public bool IsCampaign { get; set; }
    }
}
