//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.PartnerMD
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeeFood_items
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Sequence { get; set; }
        public string AvailableStatus { get; set; }
        public bool Taxable { get; set; }
        public string Photo { get; set; }
        public int Price { get; set; }
        public int MaxStock { get; set; }
        public string CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string NameTranslation { get; set; }
        public bool IsModifierGroups { get; set; }
        public string CrtUser { get; set; }
        public System.DateTime CrtDate { get; set; }
        public string ChgUser { get; set; }
        public System.DateTime ChgDate { get; set; }
        public Nullable<System.Guid> ItemId { get; set; }
        public bool IsCampaign { get; set; }
        public bool IsTopping { get; set; }
    }
}
