//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.PartnerMD
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrabFood_orders
    {
        public string OrderID { get; set; }
        public string MerchantID { get; set; }
        public string PartnerMerchantID { get; set; }
        public string ShortOrderNumber { get; set; }
        public System.DateTime OrderTime { get; set; }
        public string State { get; set; }
        public string RawData { get; set; }
        public string Message { get; set; }
        public System.DateTime CrtDate { get; set; }
        public System.DateTime ChgDate { get; set; }
        public bool MarkOrderAsReady { get; set; }
    }
}
