//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.PartnerMD
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrabFood_modifier_group_name
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GrabFood_modifier_group_name()
        {
            this.GrabFood_modifier_group = new HashSet<GrabFood_modifier_group>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string AvailableStatus { get; set; }
        public string CrtUser { get; set; }
        public System.DateTime CrtDate { get; set; }
        public string ChgUser { get; set; }
        public System.DateTime ChgDate { get; set; }
        public int SelectionRangeMin { get; set; }
        public int SelectionRangeMax { get; set; }
        public bool IsCampaign { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrabFood_modifier_group> GrabFood_modifier_group { get; set; }
    }
}
