//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.PartnerMD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemToppingMapping
    {
        public string PartnerCode { get; set; }
        public string AppCode { get; set; }
        public string StoreNo { get; set; }
        public string ItemNo { get; set; }
        public string ToppingNo { get; set; }
        public decimal UnitPrice { get; set; }
        public bool IsRequired { get; set; }
        public bool IsApplyAll { get; set; }
        public int MinQuantity { get; set; }
        public int MaxQuantity { get; set; }
        public bool Blocked { get; set; }
        public System.DateTime CrtDate { get; set; }
        public System.DateTime ChgeDate { get; set; }
        public bool IsSync { get; set; }
        public bool IsSetQuantity { get; set; }
        public string SyncResults { get; set; }
        public string Id { get; set; }
        public string SyncSetQuantity { get; set; }
        public string Action { get; set; }
    }
}
