//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.PartnerMD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSalesOnApp
    {
        public string PartnerCode { get; set; }
        public string AppCode { get; set; }
        public string ItemNo { get; set; }
        public string ItemName { get; set; }
        public string Uom { get; set; }
        public decimal UnitPrice { get; set; }
        public bool Blocked { get; set; }
        public bool IsSync { get; set; }
        public string Size { get; set; }
        public string ItemGroup { get; set; }
        public string ItemGroupName { get; set; }
        public System.DateTime CrtDate { get; set; }
        public System.DateTime ChgeDate { get; set; }
        public string StoreNo { get; set; }
        public bool IsApplyAll { get; set; }
        public string Description { get; set; }
        public int PictureId { get; set; }
        public string SyncResults { get; set; }
        public string Id { get; set; }
        public string ParentCode { get; set; }
        public Nullable<bool> IsTopping { get; set; }
        public bool IsSales { get; set; }
        public int DishId { get; set; }
        public string CupType { get; set; }
        public string Action { get; set; }
    }
}
