//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.PartnerMD
{
    using System;
    using System.Collections.Generic;
    
    public partial class MappingDataPartner
    {
        public string AppCode { get; set; }
        public string ItemNo { get; set; }
        public string ItemName { get; set; }
        public string Uom { get; set; }
        public bool IsSync { get; set; }
        public string Description { get; set; }
        public int PictureId { get; set; }
        public int RefId { get; set; }
        public string Action { get; set; }
        public System.DateTime CrtDate { get; set; }
        public System.DateTime ChgeDate { get; set; }
        public System.Guid Id { get; set; }
        public string StoreNo { get; set; }
    }
}
