//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.PartnerMD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PartnerMDEntities : DbContext
    {
        public PartnerMDEntities()
            : base("name=PartnerMDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GrabFood_categories> GrabFood_categories { get; set; }
        public virtual DbSet<GrabFood_items> GrabFood_items { get; set; }
        public virtual DbSet<GrabFood_modifier> GrabFood_modifier { get; set; }
        public virtual DbSet<GrabFood_modifier_group> GrabFood_modifier_group { get; set; }
        public virtual DbSet<GrabFood_modifier_group_name> GrabFood_modifier_group_name { get; set; }
        public virtual DbSet<GrabFood_orders> GrabFood_orders { get; set; }
        public virtual DbSet<GrabFood_service_hours> GrabFood_service_hours { get; set; }
        public virtual DbSet<ItemSalesOnApp> ItemSalesOnApps { get; set; }
        public virtual DbSet<ItemToppingMapping> ItemToppingMappings { get; set; }
        public virtual DbSet<MappingDataPartner> MappingDataPartners { get; set; }
        public virtual DbSet<Shopee_dish> Shopee_dish { get; set; }
        public virtual DbSet<Shopee_dish_group> Shopee_dish_group { get; set; }
        public virtual DbSet<Shopee_dish_group_detail> Shopee_dish_group_detail { get; set; }
        public virtual DbSet<Shopee_restaurant> Shopee_restaurant { get; set; }
        public virtual DbSet<Shopee_topping> Shopee_topping { get; set; }
        public virtual DbSet<Shopee_topping_group> Shopee_topping_group { get; set; }
        public virtual DbSet<ToppingSalesOnApp> ToppingSalesOnApps { get; set; }
        public virtual DbSet<BeeFood_categories> BeeFood_categories { get; set; }
        public virtual DbSet<BeeFood_items> BeeFood_items { get; set; }
        public virtual DbSet<BeeFood_modifier> BeeFood_modifier { get; set; }
        public virtual DbSet<BeeFood_modifier_group> BeeFood_modifier_group { get; set; }
        public virtual DbSet<BeeFood_modifier_group_name> BeeFood_modifier_group_name { get; set; }
        public virtual DbSet<BeeFood_notify_new_order> BeeFood_notify_new_order { get; set; }
        public virtual DbSet<GrabFood_store> GrabFood_store { get; set; }
        public virtual DbSet<BeeFood_restaurant> BeeFood_restaurant { get; set; }
        public virtual DbSet<Zalo_store> Zalo_store { get; set; }
    }
}
