//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.DBRead.CentralSales
{
    using System;
    using System.Configuration;
    using System.Data.Entity;
    using System.Linq;
    using System.Data.Entity.Infrastructure;

    public partial class ReadCentralSalesContainer : DbContext
    {
        public static string setDB1 = @"" + ConfigurationManager.AppSettings["setDB1"];
        public static string setDB2 = @"" + ConfigurationManager.AppSettings["setDB2"];
        public static string setDB1_Read = @"" + ConfigurationManager.AppSettings["setDB1_Read"];       
        public ReadCentralSalesContainer()
            : base("name=ReadCentralSalesContainer")
        {
        }

        public ReadCentralSalesContainer(string IPServer)
           : base("name=" + (IPServer == setDB1 ? "SetDB1_CentralSale"
                          : (IPServer == setDB2 ? "SetDB2_CentralSale"
                          : string.IsNullOrEmpty(IPServer) ? "Read_SetDB1_CentralSale"
                          : (IPServer == setDB1_Read ? "Read_SetDB1_CentralSale"
                          : "Read_SetDB1_CentralSale")))
                         )
        {

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    }
}
