//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.IFSAP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigXML
    {
        public int ID { get; set; }
        public string TransType { get; set; }
        public string RootName { get; set; }
        public string FolerPathSaveFile { get; set; }
        public string FolderPathBackup { get; set; }
        public string FileXSLT { get; set; }
        public string FolderPathReadFile { get; set; }
        public string NamespaceURI { get; set; }
        public string Prefix { get; set; }
        public Nullable<bool> IsXSLT { get; set; }
        public string ProcedureName { get; set; }
        public string KeyColumnName { get; set; }
        public string FolderPathError { get; set; }
        public string FolderFTP { get; set; }
        public string ScheduleType { get; set; }
        public string PrefixFileName { get; set; }
        public string ProcedureNameRetry { get; set; }
        public string ProcedureNameHome { get; set; }
        public string ProcedureNameHomeRetry { get; set; }
        public string FolderCopy { get; set; }
    }
}
