//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCM.BLUEPOS.Data.EF.IFSAP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int ID { get; set; }
        public string TransType { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public string MessageError { get; set; }
        public string ReadWrite { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<int> TotalFilesFTP { get; set; }
        public Nullable<int> TotalFilesSuccess { get; set; }
        public Nullable<int> TotalFilesFail { get; set; }
        public string ProcessID { get; set; }
    }
}
